{100}{}{This is biker.}
{101}{}{You see a steep bruiser-biker. He doesn't care at all.}

#Attempt to talk
{110}{}{Dude, there are no strangers here !}
{111}{}{Ouch, get lost!}
{112}{}{Get lost, ye nugget, I don't have time for this.}
{113}{}{Well? What are you staring at?}
{114}{}{Wanna bite me?}
{115}{}{::burps::}
{116}{}{Damn, I'm in a bad mood today.}
{117}{}{Open you mouth, and I'm gonna shoot you dead!}
{118}{}{Fucking great, guys. Another one arrived!}
{119}{}{Don't come across us in bars, we like to make a hassle there.}
{120}{}{Haven't seen for Jay Kukish for a long time.}

#Pop-up dialogue
{200}{}{Take one ride on the chopper - and you'll never want to trample over the Wasteland with boots...}
{201}{}{The car carries the body, but bike carries the soul...}
{202}{}{The Lord didn't fail, changing the steel bird to an iron horse...}
{203}{}{Live for riding, riding for a living...}
{204}{}{We are just like devils on wheels!}
{205}{}{The best music is the roar of our engines.}
{206}{}{Gasoline replaced blood in our veins long ago...}
{207}{}{Our essence - brutality... Our God - hatred...}

#Female character:
{1110}{}{Gal, there are no strangers here !}
{1111}{}{Ouch, get lost!}
{1112}{}{Get lost, ye horse, I don't have time for this.}
{1113}{}{Well? What you're starring at?}
{1114}{}{Wanna suck on me?}
{1115}{}{::burps::}
{1116}{}{Damn, I just crapping over my *crappy* mood!}
{1117}{}{Who opens mouth - will be shot at sight!}
{1118}{}{Fucking great, guys. Another one arrived!}
{1119}{}{Don't come across us in bars, we like to make a hassle there.}
{1120}{}{Haven't seen for Jay Kukish for a long time.}