{100}{}{You see a raider.}
{101}{}{You see a member of the "Ferocious Molerats".}

#Pop-ups
{110}{}{We're the Ferocious Molerats, motherfucker!}
{111}{}{Now we're fucking unstoppable!}
{112}{}{Hell of a setup we've got here, huh?}
{113}{}{Who's bad? We're bad! We own this fucking desert!}
{114}{}{And that's what it means to be a Molerat!}
{115}{}{Scared, bitch? Heh. I knew it.}
{116}{}{Dumb motherfuckers hiding in a corner, like children.}

{120}{}{I smell a caravan merchant!}
{121}{}{Move! Here they come!}
{122}{}{Oh yeah! We fucking wrecked those bitches!}
{123}{}{Oof, I'm tired. And hungry!}
{124}{}{Tell everyone in Black Rock what you saw here. Leave nothing out! Tell them NOTHING will end the reign of the Ferocious Molerats!}
