{100}{}{You see a local.}
{101}{}{You see one of Black Rock's citizens.}

###############################################################
#
#              Pop-ups
#
###############################################################

#Jed died
{102}{}{I knew Jed would die soon.}
{103}{}{Jed's done so much for us. I hope he's in a better place.}
{104}{}{Not many people get to die of old age nowadays.}
{105}{}{Jed always said, "When I die, send me to the heavens." Whatever that means.}
{106}{}{I dreamed that Smith was in heaven, but it was full of tribals. Bad luck.}

#Jed's alive
{107}{}{Jed doesn't have much time left. I can feel it.}
{108}{}{If Jed dies, I may cry. You know... Just a little.}
{109}{}{The heavens are waiting for Jed... Ah, whatever.}

#Robbed graves reactions
{110}{}{They say some outsider is digging up the graves, but I think it's Bob.}
{111}{}{If I wake up to find one more defiled grave... Oh, Bob's gonna get it.}
{112}{}{Bob's a good guy, but he needs to learn how to control himself.}
{113}{}{}
{114}{}{}

{115}{}{When I die, I hope geckos get to my body before Bob does.}
{116}{}{We have to bring Bob to justice! How many times will he defile our dead?}
{117}{}{Bob's a good guy, but he needs to learn how to control himself.}
{118}{}{}
{119}{}{}

#Mike's outcomes
{120}{}{Mike was one of our best hunters! Why did you do this?!}
{121}{}{Did you really have to kill Mike?!}
{122}{}{How could you kill Mike?!}
{123}{}{I liked Mike, but I knew this would happen eventually.}
{124}{}{}

{125}{}{Mike sure loves to fight.}
{126}{}{If there's one guy in town you shouldn't mess with, it's Mike.}
{127}{}{Mike is going to get drunk and go looking for a fight again.}
{128}{}{That Mike really needs an ass-kicking.}
{129}{}{}

{130}{}{Oh, did Mike beat you? Ha! Must have been fun.}
{131}{}{Damn, Mike really beat your ass, didn't he?}
{132}{}{Man, I was really hoping for someone to kick Mike's ass. Too bad.}
{133}{}{Don't give up. Mike hasn't been beaten since... Hmm, a couple of days ago, maybe.}
{134}{}{}

{135}{}{Were you the one that beat up Mike? It's an honor!}
{136}{}{So you beat Mike, huh? That's impressive.}
{137}{}{Hey, good job on Mike!}
{138}{}{That should keep Mike from going looking for a fight for a while.}
{139}{}{Hahaha!! You kicked Mike's ass! High five!}

#When character is a raider
{140}{}{There's been more raiders around lately. Hmm, how do I know you're not one of them?}
{141}{}{Raiders aren't welcome here.}
{142}{}{Raiding ain't a life that ends well.}
{143}{}{May god strike me down if I don't kill at least one raider this month!}
{144}{}{}
{145}{}{If raiders attack the next caravan, we won't get another.}
{146}{}{More raiders this morning. How long is this going to go on?}
{147}{}{I wish those raiders would just die.}
{148}{}{}
{149}{}{}

#Pop-ups
{150}{}{Uh, hi.}
{151}{}{What a shitty day. Just like yesterday.}
{152}{}{Don't shake my hand. I was just in the toilet.}
{153}{}{It's getting crowded around here.}
{154}{}{You aren't gonna settle down here, I hope?}
{155}{}{Have you met William? He's a good guy. Not a lot of sense, though.}
{156}{}{You talked to Justin yet? A harsh man, but irreplaceable.}

#Brahmin
{157}{}{How could a whole brahmin just disappear?}
{158}{}{If I were William, I'd kick his boy's ass.}
{159}{}{Only in Black Rock could a whole brahmin just disappear.}

#Fugitive slaves
{160}{}{Those slaves are nothing but trouble.}
{161}{}{Slaves belong with their master, not in Black Rock!}
{162}{}{The slaves are finally gone? That's good to hear.}
{163}{}{If we'll get any more escaped slaves, we'll do the same thing.}
{164}{}{Has William lost his damn mind? We don't need escaped slaves hiding around here!}
{165}{}{William took in those slaves? He's too soft.}
{166}{}{Well, I guess there's no danger if those slaves' collars are gone.}
{167}{}{Those slaves shouldn't be a problem anymore, but who knows?}
{168}{}{}
{169}{}{}

#Main quest of Black Rock
{170}{}{Damn! William was really counting on that caravan... }
{171}{}{It's too bad that caravan deal fell through.}
{172}{}{I was hoping to buy something new from those caravans, too... }
{173}{}{I guess we won't be getting mail from Reno any time soon.}

{174}{}{Whoever saved that caravan must be one bad mother.}
{175}{}{Finally, things are looking up!}
{176}{}{I'm really getting sick of all these caravans.}

{177}{}{I heard William is waiting on Milo. He's not usually this late.}
{178}{}{I wouldn't be surprised if Milo just ran away from his wife. Ha!}
{179}{}{I haven’t seen Milo for a long time.}

###############################################################
#
#              Talk with dave about pistol
#
###############################################################

{199}{}{You see Dave.}

{200}{}{[He smiles and nods] Welcome! Always happy to see people like you in this shithole.}
{201}{}{[He peers at you suspiciously] New in town? Interesting... Anyway, what do you want from me?}
{202}{}{Are you Dave?}
{203}{}{Nothing.}
{204}{}{Ohh, I can't hide it anymore! I am... Dave. Everyone knows that, and now, so do you. Shit, how could it be so hard to hide in such a small settlement?}
{205}{}{Quit screwing around. Do you know anything about this pistol?}
{206}{}{Ah, yeah... My trusty partner Smiley would sometimes hunt with it. He was lucky, but not lucky enough to save him from raiders. We divvied up his stuff to sell, and that damned merchant William took the best of it, of course. But he made a mistake.}
{207}{}{Which was?}
{208}{}{He forgot that it needs batteries! No one's going to buy a plasma pistol you can't power. Also, it's not as good as it seems. Smiley had to fix it up constantly just to keep it working.}
{209}{}{Do you know how to fix it up?}
{210}{}{Hmm... [he rubs his chin] Well, I saw him clean it all the time. I must be the only one - no one even tried to maintain it after Smiley died. I'll be honest, that thing's never going to be a real killer, but with a bit of work you might get more "oomph" out of it.}
{211}{}{That sounds great. Can you do that?}
{212}{}{Sure... But it's gonna cost you.}
{213}{}{What do you want?}
{214}{}{William on my back about gecko skins, but hunting's been lean lately. Get me about, oh, 250 bucks' worth of skins and I'll clean that baby right up.}
{215}{}{Let's talk about the pistol again.}
{216}{}{What types of gecko skin does William want?}
{217}{}{I'll go, then.}

{218}{}{Golden gecko skins are more valuable than silver ones, but any will do. I just need to get William off my back.}
{219}{}{Here's a silver gecko skin.}
{220}{}{Take a golden gecko skin.}
{221}{}{Look! I have an acid gecko skin.}

{222}{}{Great! That's enough. Give me the pistol and I'll fix it up right away.}
{223}{}{Here you go. It had better be worth it.}
{224}{}{Good, but this isn't enough. Bring me more.}

{225}{}{[Dave carefully disassembles, cleans, and calibrates the weapon. Sometimes he seems not to know what he's doing, but finally, he reassembles the pistol and hands it to you.] Well, what did I tell you? Only I can fix it!}
{226}{}{Good work, Dave. Nevada's going to be a lot emptier soon.}
{227}{}{Thanks, Dave. You really helped me out.}
{228}{}{No, this won’t cut it.}
{229}{}{Don't mention it. It was nothing.}

#{230}{}{Dave, what do you know about energy weapons?}
#{231}{}{Not much. The big cities might have some pre-war magazines you can look through.}
#{232}{}{Tell me about Smiley and raiders - what happened?}
#{233}{}{We were coming back from a hunt in Lovelock. Raiders ambushed us and demanded food. They looked tired and hungry, and there weren't a lot of them, so we just shot them. Smiley was critically wounded in the fight. Sucks, huh?}
#{234}{}{Lovelock? Where is that?}

{235}{}{What now?}
{236}{}{I'll see you later, when I have the pistol.}
{237}{}{I'll do it as soon as you bring the pistol.}
{238}{}{I already told you, William's on my ass about gecko skins. Bring me about }
{239}{}{ dollars' worth, and I'll fix up that pistol for you.}

###############################################################
#
#              Talk with Bolt
#
###############################################################

{250}{}{You see Bolt.}
{251}{}{[He peers at you] What?}
{252}{}{Uh, nothing. Nothing at all.}
{253}{}{Are you Bolt?}

{254}{}{That's what they call me. What do you want?}
{255}{}{Why do they call you Bolt?}
{256}{}{What were you doing on the night the brahmin disappeared?}
{257}{}{[He smirks] Maybe it's because I have a metal spark in my eyes.}
{258}{}{Sleeping, like I should have been. Don't pull any psychological crap on me - I didn't have anything to do with that fucking brahmin. Full stop.}
{259}{}{Bolt, can I see your shotgun shells?}
{260}{}{Err, my shotgun shells? Uh, why?}
{261}{}{I want to compare them with the ones left in the stolen brahmin's body.}
{262}{}{[Looks around furtively and whispers to you] How the fuck... Dammit! I knew I'd get in trouble for this shit!}
{263}{}{Interesting. What do you have to say in your defense?}

{264}{}{Fuck it, I won't even try! I'm not that kind of person. You know what kind of person I am? I'm one of the "Molerats" gang, that's what! Well, *was* a Molerat. I'm retired... Or I thought I was, anyway.}
{265}{}{Tell about the gang.}
{266}{}{You left the gang?}
{267}{}{How is this connected to the missing brahmin?}
{268}{}{What are you going to do now?}
{269}{}{I have to decide what to do next.}
{270}{}{A bunch of scumbags, that couldn't hack it in Gerlach or Black Rock, but had enough ammo to feed themselves in the mountains. Not very glamorous, but you gotta eat.}
{271}{}{Yeah. We controlled this whole valley once, but by the time I left, we were shaking down random travelers for crumbs. I came back here, and until you figured me out, no one knew about my past.}
{272}{}{The guys hadn't eaten in a while, so they came to me one night. I couldn't say no - they're weaker than they were, but they're sure as hell still tough enough to kill me! I mixed xander root powder into some water and gave it to that kid so he'd fall asleep, then managed to get the planks off the fence to get the brahmin out without making noise.}
{273}{}{Nothing. If they're gonna toss me out, so be it. I'll go to Big Louie and join up with him. It won't be as good as here, but at least I won't starve to death, like the Molerats. They don't have much time left.}
{274}{}{Not much time left? Why not get rid of them right now?}
{275}{}{I know what you're thinking - get a posse together and take those guys out, right? Not a chance, buddy - that only happened in old movies. The gang's well hidden in the mountains, you won't get them that easily. I'll tell you this, though - if William gets that caravan route going, then that'll put some life back into the gang.}
{276}{}{I'm going to tell everyone the truth, unless you can convince me not to.}
{277}{}{Oh, lah-dee-dah! Fuck that. William won't kill me, he'll just cast me out. So I'm breathing freely - see? [he inhales deeply] I smell adventure!}

{280}{}{I talked to William. He forgives you and says you can stay.}
{281}{}{William's furious. You have to leave Black Rock.}
{282}{}{He forgives me? After what I did? I... Hmm. I didn't expect that. But if that's what he says... Look, thanks. You did a good thing for me, better than I deserve.}
{283}{}{Yeah, I won't say I don't deserve it. I'll pack up and go. I tried to go straight, but I couldn't - and that's fine. Tell William that, whether I'm here or not, the gang will be back. He'd better be ready.}
{284}{}{Enjoy your life here.}
{285}{}{Just shut up and go.}

{286}{}{I have to do what I can to fix this.}
{287}{}{You won't see me around here again.}

#Female character
{1101}{}{You see one of Black Rock's citizens.}
{1275}{}{I know what you're thinking - get a posse together and take those guys out, right? Not a chance, girl - that only happened in old movies. The gang's well hidden in the mountains, you won't get them that easily. I'll tell you this, though - if William gets that caravan route going, then that'll put some life back into the gang.}
{1280}{}{I talked to William. He forgives you and says you can stay.}
