{100}{}{Hey, kid, what the fuck do you want there?!}
{101}{}{Locked, and you can't see any locks.}
{102}{}{Gate does not have a visible lock. Perhaps is can be opened from another place.}
{103}{}{The door is trapped.}
{104}{}{This does nothing.}
{105}{}{The gate is broken.}
{106}{}{Strange, but there just nowhere to insert the key. Maybe it locks somehow different?}
{107}{}{Gate opens somehow else, skills are useless here.}
