{100}{}{Unsurprisingly, the brahmin is just as dead as when you last saw it.}
{101}{}{You've found the missing brahmin - or, rather, what's left of it. Nothing remained, but its heads and hooves. They already stink of rot.}
{102}{}{[Look closely]}
{103}{}{Enduring the nauseating stench, you find that both skulls have a jagged hole in them, ringed with gunshot residue. Inside the skulls are pieces of nails, probably from homemade shotgun shells.}
{104}{}{Interesting...}
