{100}{}{The leader of the Coyote tribe.}
{101}{}{You see a damn attractive and just as rude person.}

{110}{}{You will burn on the sacrificial fire}
{111}{}{I'll eat your heart to become stronger}
{112}{}{Come on, my children!}
{113}{}{Kill! Kill!}
{114}{}{My children, if you are hungry, take yourself the most delicious!}
{115}{}{The meat of strangers is so delicious}
{116}{}{I like you. Especially your sirloin part.}
{117}{}{Come on, run! You will only provoke my children!}
{118}{}{Nobody will be forgiven, if this prey gets away!}
{119}{}{A glorious dinner today, my children! Rejoice!}
