{100}{}{You see a feral ghoul.}
{101}{}{You see an agent of now extinct patrol unit. Seems like he is not going for retirement anytime soon.}

{110}{}{Let me introduce myself - Michael Dixon, agent of patrol unit.}
{111}{}{Show me the papers, before I apply force}
{112}{}{Get out of the car and place your finger on your nose}
{113}{}{It seems to me that you're drunk. The punishment is amputation of the both hands.}
{114}{}{I won't be surprised if you are involved in the transport of Mexican illegals}
{115}{}{Surrender your weapon, before I call reinforcements}
{116}{}{I'm forced to take extreme measures}
{117}{}{I'll ask the first and last time...}
{118}{}{I'm confiscating your vehicle}
{119}{}{Resistance is futile}