{100}{}{You see your pursuer.} 
{101}{}{You see a mercenary hunting for a filter you're delivering to Salt Lake.}

{110}{}{Give me the filter while you're still in one piece!}
{111}{}{You won't get out of here until you give back the filter!}
{112}{}{This thing in your backpack will be mine!}
{113}{}{Heading over to Salt Lake? May I carry your stuff?}
{114}{}{For this filter Salt Lake will pay huge money}
{115}{}{Hey, shut up and give away the filter!}
{116}{}{Sorry but I need this filter more than you}
{117}{}{"Stand still!" - this is what usually said when robbering?}
{118}{}{This thing is too heavy, you'll struggle to drag it to the city. Don't mind giving it to me?}
{119}{}{Walking with this filter is quite dangerous, don't you think?}
{120}{}{Even though I'm a caravaneer, I don't mind easy money}
{121}{}{Choose: filter or live?}