{100}{}{You see a king.}
{101}{}{You see one of the members of the "Kings" gang.}

{110}{}{You shouldn't have come into this area}
{111}{}{Here *we* are the kings!}
{112}{}{You will have to pay for passage on our turf}
{113}{}{Uh, the racketeering becomes harder lately}
{114}{}{I'm not a gangster, but the band decided otherwise}
{115}{}{Give us the money and get the fuck out!}
{116}{}{What, do the lights of Vegas beckon you? Too bad...}
{117}{}{The boss will be happy, if I take a couple of coins of you}
{118}{}{We are the kings here, so behave!}
