{100}{}{You see a feral robot servant.}
{101}{}{You see the robot servant from the "Mr. Handy" series. Probably, this one has lost its owners sixty years ago.}
{102}{}{ }

{110}{}{Want to hear a joke, Mr. McClennan?}
{111}{}{Good morning, Mrs. McClennan.}
{112}{}{Same scum like you killed Mrs. McClennan!}
{113}{}{Away from the home of family McClennan!}
{114}{}{Save yourself, Mr. McClennan! Go to the basement and take the children!}
{115}{}{I won’t let you hurt my masters!}
{116}{}{No one can interrupt the morning dog walk. You will have to pay a fine.}
{117}{}{I see a thief! Master, do not leave the room and lock the door!}
{118}{}{You shouldn't have kidnapped the dog of my master!}
{119}{}{Oh, this blinding flash... Mr. McClennan? What's wrong with you? Mr. McClennan!}
{120}{}{I can't cause harm to the family members of McClennan, but you're not of their family!}
{121}{}{I was made to obey orders of a human, but only if that person is a family member of McClennan!}
{122}{}{I must protect, because I the family property of McClennan.}
{123}{}{It will be a gentle rain!!!}
{124}{}{Your blood is a great lubricant, error!}
{125}{}{Activate Protocol "Deep cleaning"}
{126}{}{Place the skull of this primate next to your trophies, Mr. McClennan?}
{127}{}{Serve the intruder with garlic or mustard sauce, Mrs. McClennan?}
