{100}{}{This is Neon Gangster.}
{101}{}{You see a bandit known as Neon Gangster.}

{110}{}{My motto is "Live bright and die bright!"}
{111}{}{Prepare to become a shadow in this lightshow}
{112}{}{Lights of Vegas, reincarnated as me, will burn you down}
{113}{}{This city will tremble in fear only hearing my name. This is what I call "bright personality"!}
{114}{}{Want to hit me? It's like trying to hit a sun}
{115}{}{The moon illuminate your body on the roadside at night}
{116}{}{My weapon was made to enforce law and order. I'll enforce chaos with it.}
{117}{}{I hate killing cowards. So you have to be braver. C'mon!}
{118}{}{Do you know what "homocentric beam of light" means? You will...}
{119}{}{It's simple: You'll be killed by the induced emission of an optical quantum generator.}
