{100}{}{Hunter-cannibal.}
{101}{}{Hunter of Coyotes tribe. He preys on you and other animals from the outside world.}

{110}{}{Fresssh meeeat!}
{111}{}{Boones and meeat!}
{112}{}{Outlander, you will diiie!}
{113}{}{I will feed my family with you!}
{114}{}{This one is resisting!}
{115}{}{Good catch!}
{116}{}{The savages of the outside world became more appetizing!}
{117}{}{Take the savage!}
{118}{}{You, savages, you only good for food!}
{119}{}{Oh, new sacrifice for the God of windmills!}
