{100}{}{You see a punk.} 
{101}{}{You see a punk with a very aggressive attitude. It seems that he is under the influence of drugs.}

{110}{}{I'll dance on your grave!}
{111}{}{We, the cocaine vacuums of Salt Lake, are against the drunks of Las Vegas!}
{112}{}{I'm in a plastic world eating plastic cereal.}
{113}{}{If people don’t like me, then I don't like people.}
{114}{}{I'm fighting against the system... Actually, no, I'm just fighting.}
{115}{}{I think all people in the neighborhood would look better with a hole in the head}
{116}{}{I'm 18, so I can say "fuck you!!!"}
{117}{}{Hey, look! It's like the Devil took a shit and it landed right here!}
{118}{}{I'll break the system! Starting with you!}
{119}{}{For a bottle of beer we'll skin you alive.}
