{100}{}{You see a rednecks.}
{101}{}{You see a redneck that stepped on the path of robbery and burglary, out of desperation.}

{110}{}{Halt! This is a robbery!}
{111}{}{Don't you dare resist, or else... Or else!..}
{112}{}{I don't want to kill, but I'll have to do this}
{113}{}{I need to kill someone to feed my family}
{114}{}{Don't be greedy, share with the poor, rich bastard!}
{115}{}{You pretend to be poor, but your gentle hands gave you away}
{116}{}{I can smell a rich scum like you from a mile away}
{117}{}{Money! Now!}
{118}{}{This year was bad. That's why you will cover the losses.}
{119}{}{I'm not going to work from morning till evening, if people with a fat wallet pass by me}