{100}{}{You see a prisoner.}
{101}{}{You see a badly tortured prisoner.}

{102}{}{H-help me! P-please! Don't leave me here!}
{103}{}{I'm all w-wounded... Won't last long... Do you have a stimpak or something to fix my bad condition?}

{104}{}{Thanks, friend! I'll return to the city and tell everyone about the one who saved me.}
{105}{}{How did you end up here?}
{106}{}{What Harrelson did to you?}
{107}{}{What do you know about Harrelson?}
{108}{}{Bye.}

{109}{}{I'm an unemployed resident of Salt Lake. When I lost my job, the Quok brothers advised me to go here, they said that there lived a frail old man with good belongings. And I took the bait. At the entrance I fell into the trap, then Harrelson raked me in the cave.}
{110}{}{It was damn creepy with him. It seems that he didn't do anything really, but he tickled my nerves so much that I almost went crazy! Sometimes he would sit opposite with a calm face and try to yelp about my nature. What a son of a bitch! Peeped straight into my soul, then spat and trampled ...Glad that he's dead!}
{111}{}{This bastard is hundred years old. He survived the nuclear war. He didn't talk much about himself but I didn't ask. For me it was more important to get out of here.}

#Женские реплики
{1104}{}{Thanks, friend! I'll return to the city and tell everyone about the one who saved me.}