{100}{}{You see monster.}
{101}{}{You see an ugly mutant. It seems that it's formed by merging several people and dogs.}
{102}{}{We... See... Light...}

{110}{}{Long time no dinner with the guests!}
{111}{}{We avenge the puppies!}
{112}{}{The Master was right in one thing!}
{113}{}{Hate hummies!}
{114}{}{The Master will swallow up mankind like he consumed us!}
{115}{}{No one will escape the Master's retribution!}
{116}{}{Cursed be the Master for what he did to us!}
{117}{}{Kill us!}
{118}{}{We hear your thoughts!}
