{100}{}{You see a nomad.}
{101}{}{you see an experienced nomad of Great Basin.}

{110}{}{[Frowns with dislike at the sight of you] Shouldn't be standing so close. And it's hot in here already.}
{111}{}{[Curiously looking at you] Hi! Traveling too?}
{112}{}{[Looks at you blankly] Just traveling or running from someone?}

{113}{}{I'd like to get provisions for the journey. Could you share some with me?}
{114}{}{I wonder, what people like you are doing in these uninhabited lands?}
{115}{}{I have been roaming for a while. Tell me, where is the closest town?}
{116}{}{I should probably continue my journey. Farewell.}
{117}{}{That's all I can exchange. If this is not enough, you have to go into the city.}
{118}{}{Speaking of the city. Tell me, where is it?}
{119}{}{We wander from valley to valley in search of a suitable place to live. And we came from the North-East. There is now a series of wars and devastations. Many fled from there. Surely you will meet other nomads from those places.}
{120}{}{Salt Lake City in the North. Go along the highway and you'll hit yourself straight into the city near a large lake.}