{100}{}{You see a biker.}
{101}{}{You see Jay Kukish. Yes, that one.}
{102}{}{I don't trust you, but you can be useful in battle.}

{110}{}{Hold still. Hypnotrance ray can cause a headache, but you will quickly return to normal.}
{111}{}{So, it was a trap! Let me out of here, you bastard! Now!}
{112}{}{Why do you hide behind armored glass? Maybe you'll come here and talk like a man?}
{113}{}{So, you planned it all. Probably, you were the one that closed the doors. Clever. Well, I don't have much choice now.}
{114}{}{Let's not waste time. Get to the point. Why did you do all this?}

{115}{}{[You wake up in a bright, enclosed room. You see a biker watching you through thick glass.]}
{116}{}{It’s you...}

{120}{}{Making threats won’t help you. You can't get out of here until *I* allow you to. So sit tight and don’t make any sudden moves.}
{121}{}{Or what, you'll knock me out again? Just you wait, when I get to you, I will make you feel the pain you cannot even imagine!}
{122}{}{Okay, I'm not going to resist for now. Let's talk.}
{123}{}{Well, you're pretty smart for a biker. To lure me into a trap and spring it in a not so obvious place... Are you afraid of someone?}

{124}{}{Maybe you'll get such chance. But now you're here, trapped. I brought you here to ensure our conversation.}
{125}{}{Ensure?! You're just a pussy! Hiding behind glass because you're afraid of me.}
{126}{}{I'm not going to argue with that. Let's get down to business.}
{127}{}{This is reasonable. At least we won’t shoot each other this way.}
{128}{}{Your attempt to piss me off is funny and pathetic. The kind of the reaction I expected from the residents of the vault. You're like children suffering from teenage problems and delusions far beyond your age. I'll wait until you calm down. In the end, nothing prevents me from walking away. Unlike you.}
{129}{}{You're not leaving until you spit out the truth! Tell me, bitch, tell me everything you know!}
{130}{}{Well, I'll try to calm down. While you tell me how you managed to track me down.}
{131}{}{That’s more like it.}
{132}{}{Tell me how you managed to track me down.}
{133}{}{Don’t even think about it. I won’t give you the satisfaction.}
{134}{}{Will see about that!}
{135}{}{Okay. But now tell me how you managed to track me down.}

{136}{}{[Sneers] How cute. Did you picked this up in the Wasteland? I see it shook you up pretty good during your travels... But let's not waste time on useless chatter. You can't get out of here until *I* allow you to.}
{137}{}{Oh, really? And if I try, you will knock me out, you pathetic coward? Wait until I get to you, and you'll see what I do!}
{138}{}{Exactly. You can't get out of here until *I* allow you to. So, do not waste time on empty chat.}
{139}{}{Okay! Enough talk, let's settle this with a fight like men! With fists!}
{140}{}{Finally, I hear the voice of reason in your childish talk. Notice that I yet to threaten you. The hypnotrance trap was set after you turned the signal jammer, I brought you here to ensure our conversation.}
{141}{}{[Grimly nods] Nobody can be trusted in this world. Want to talk to me - will have to stick to my rules. Note that I'm not threatening you. Hypnotrance trap was set after you turned the signal jammer, I brought you here to ensure our conversation.}

{142}{}{There was a bug planted in your Pip-Boy. Most likely it’s in all portable Pip-Boy devices, which were given to the inhabitants of the Vault 8. With its help, I tracked you, but so could someone else. Signal jammer allowed this problem to be temporarily resolved. Don't worry, I already dismantled the bug, just in case.}
{143}{}{Who else knew about this? Your friends, the bikers from Bridgeport?}
{144}{}{Lies! You just warned these bikers from Bridgeport, right?}
{145}{}{No. I have a strained relationship with my brothers. We went separate ways. Although, I'm not hiding it - it is I who made the rumor that there's something big about to happen in Hawthorne.}
{146}{}{}
{147}{}{Is there really something that should happen?}
{148}{}{You're hiding on this base without a reason! Protection, monitors, traps - all necessary arsenal for a true coward.}

{149}{}{Hawthorne was a military base before the great War. Military itself mothballed it and left, and the small local population gradually died out. Many prospectors tried to reach the resources of this base... But it would be better for them to stay away. Anyway, I'm here for another reason. The whole story with the Vault 8 is clearly associated with the military and the government. I came here in search of information.}
{150}{}{Okay, stop. So you yourself know nothing? Why then did you steal the device from the vault?}
{151}{}{I don't understand. You will have to start from the beginning of all these events.}
{152}{}{Oh yeah... You don't remember, right? The employer warned me...}
{153}{}{Dr. Willmouth works wonders! He restored my memory, and can save from radiation. Yes, he is a wizard. And he has an Autodoc.}
{154}{}{Doctor at the vault gave me the memory with the help of the Autodoc. And when I get out of here, you'll be sorry that he did it.}
{155}{}{You seem to be properly briefed, but did not consider the possibility of memory recovery with the help of the Autodoc in the vault.}

{156}{}{And you believe that? Autodoc can't conduct such a serious operation. I've seen more sophisticated devices, but even they were not able to change the consciousness of the patient. And to erase the memory... [suddenly grins] to erase it, Autodoc is not an option. Most likely, there's something else going on in your vault, that you don't know about and what fell out of your consciousness, while Doc did his "experiments" on you.}
{157}{}{I suppose... Wait a minute! Hypnotrance trap, Autodocs, memory... You son of a bitch, it's because of you I lost my memory!}
{158}{}{I believe in the honesty of doctor Willmouth! And your stupid grin only shows that you are disingenuous and hide something. Weren’t it you the one that erased my memory?}
{159}{}{It doesn't matter. What happened, has happened. Now I'm interested more in what you did with the stolen device.}

{160}{}{The employer himself has deprived you of memory. I only used your body as an excuse to enter the vault.}
{161}{}{So, what happened in the vault?}
{162}{}{Should have known you're just a pathetic mercenary. And what was your job?}

{163}{}{My goal was to get into the vault, using your body as a bait, to cut down the guards with hypnotrance and steal the device. You know it without me telling you.}
{164}{}{What were you talking about with the Overseer, before you knocked him out?}
{165}{}{What kind of device did you steal?}
{166}{}{Who's your employer?}
{167}{}{Okay, this part of the story is clear now.}

{168}{}{It was a long conversation. Basically the old man was interested in my life outside of the city, and I - in vaults and its technologies. I won't retell it all.}
{169}{}{At first, I could not understand myself. I got it only in Area 51. There was the most advanced technology I never seen anywhere else.}
{170}{}{I would like to know about it too. Who is he, where did he get your body, why would he need a device from the vault - I don't know that. But my interests were different.}
{171}{}{}
{172}{}{What do you mean?}
{173}{}{Crystal-based hard drive is very rare and a breakthrough tech, especially for the beginning of the War. What the hell it was doing in such a miserable place like a bomb vault? I could not read the data anywhere, but I believe that the disk contains programs for vault's automatic control systems. And, probably, something else, not so obvious.}
{174}{}{Why didn't you give the ordered unit to the employer?}
{175}{}{When it comes to complex pre-war technology, I don't care about employers. I decided to first figure out what it is. Such opportunity is rarely presented.}

{176}{}{If you know all this, then why the hell do you want to spend so much effort to find me?}
{177}{}{Sorry, but without the device the vault will fall to the threats of the Wasteland. I can't let that happen.}
{178}{}{Because of your technological ambitions, they kicked me out of the vault and forced me to return the device.}
{179}{}{I don't care about the vault and the device. I want to take revenge on those who started all this. And you're one of them.}
{180}{}{I was just given this assignment. The rest is not my business.}
{181}{}{Okay. It doesn't matter what's gonna happen, you can have it. I'll leave it here. I have a goal more important than your pathetic vault. Although, if you want to know more about such tech, I suggest you to visit Area 51 - a lot of beautiful things there, even better than you have already seen. [Looks at monitors next to him] Oh, and one more thing...}
{182}{}{What?}
{183}{}{We have company. And they will have to be dealt with.}
{184}{}{Wait, I want to fight! Together it will be easier.}
{185}{}{Yeah, go straight to them. I hope they torture you slowly and painfully.}
{186}{}{Hey, don't leave me here! I'm going to starve to death.}
{187}{}{If you have at least some brain, you'll find a way out. Farewell.}
{188}{}{So, you are already familiar with the vault and its inhabitants. And how do you like my home?}
{189}{}{You are all like children. It's funny to explain to people like you that Santa Claus does not exist.}
{190}{}{[End dialogue]}
{191}{}{[Only scoffs in response and goes to the elevator]}
{192}{}{Not in this lifetime. I can't trust you after this conversation. Too much ambiguity in your words. Here you playing tough and then you beg me. Either you have a mess in your head, or you take me for a fool. This will not work.}
{193}{}{Well, fuck you! I wish you die out there!}
{194}{}{That's nothing. Maybe we'll get even. Don't get caught up in my way.}
{195}{}{I'm just offering. Refuse - and you'll feel sorry later.}
{196}{}{Wait! I just don't know how to talk to you. Believe me, I want to understand all this.}
{197}{}{[Stares at you then looks at the monitor, then back at you, thinking about something] Okay. But as soon as we get out of the danger zone - we part ways. If you want to get out of here without the risk, try to sneak to the back door. It is located right near the railway gate of the hangar, try not to miss it.}
{198}{}{All right!}

{1157}{}{I suppose... Wait a minute! Hypnotrance trap, autodocs, memory... You son of a bitch, it's because of you I lost my memory!}
