{100}{}{The ruins of this old settlement give off the feel of oblivion. It's like the time has stopped in this place, since the last blast of the Great War died down.}
{101}{}{You enter Hawthorne outskirts. It's pretty quiet here.}
{102}{}{You enter a garrison territory. The silence here makes you nervous.}
{103}{}{}
{104}{}{Marauders, fucking assholes, they already been here}
{105}{}{This military store was long ago looted by prospectors.}
{106}{}{}
{107}{}{Hey, looks like this generator still works...}
{108}{}{Looks like the greedy prospectors accidentally activated the security systems. Now the city is full of hostile robots.}
{109}{}{Your Pip-Boy received a message from Jay Kukish.}
{110}{}{Wha... How is this possible?!}
{111}{}{This building is in a state of emergency. Obviously, it haven’t been looked after for a long time.}
