{100}{}{You see child.}
{101}{}{You see a local child - perhaps a pledge for a bright future of this town or it's desolation.}
{102}{}{You did a bad thing offering drugs to a child. Your soul became a bit blacker.}
{103}{}{Hello}

{110}{}{Hi.}
{111}{}{This purse is sticking out of your pocket? It's yours?}
{112}{}{Bye.}
{113}{}{Yup. So what?}
{114}{}{Well, it's true? Maybe some trader lost it, and you just happened to "find" it, huh?}
{115}{}{And what's your deal? If you want it - I can sell it. For 10 bucks.}
{116}{}{That's fair. Here's 10 buck for the find, now give me the purse.}
{117}{}{Wow! That's great!}
{118}{}{So where did you find it?}
{119}{}{Yeah. Take care.}
{120}{}{Alright, nevermind.}
{121}{}{Some of ours found it. Then it went from hand to hand. I don't know who was the first.}
{122}{}{Right. Now all ties are lost.}
{123}{}{Well-well, keep talking you little thief.}
{124}{}{You better stop deceiving adults. It might end bad. Give me the purse while the real owner didn't show up.}
{125}{}{No way!}
{126}{}{Well... Okay, take it, just don't tell anyone about me!}
{127}{}{Okay.}
{128}{}{If you'll argue with me - I'll take you by the neck and take to the sheriff, you understand it? Now give back stranger's thing!}
{129}{}{But it's not me, I swear! Here, take it, just don't tell anyone about me! Please!}
{130}{}{And I'll call the cops right now and say that you are molesting me!}