{100}{}{You see a storekeeper.}
{101}{}{You see the manager of the factory warehouse.}

{110}{}{Hey-hey! Not allowed! This is service room. Get out! Move, move!!!}
{111}{}{Alright, I'll leave.}
{112}{}{I will go out this time, but be aware that I might punch you in teeth next time.}

{113}{}{Calm down, I'm here for the batch of product.}
{114}{}{It's not a store... Wait, so that's what it is. Well, sorry. But I haven't see you before. Show me your license, some like to impersonate as couriers...}
{115}{}{Here, look.}
{116}{}{Eh, I don't have it with me right now.}

{117}{}{So free my ears from your drivel! Bring license or get out! Here you do not shop! Bloody beggars, I'm so sick of...}
{118}{}{(Leave)}
{119}{}{That's better! Sorry for being rude, there are lots of beggar recently appeared. I've been telling these fools for a long time - just make the accounting system. But they are all busy... So, how many bottles do you need for today?}
{120}{}{How much I can order?}
{121}{}{Ah yes, you're new here. Listen to me, I'll explain once. Now, I roll these boxes to the entrance and put a lock, so in the future we hadn't see each other and hear each other. Then everything goes according to the standard application, we don't even have to contact. You pay at a wholesale price - I am replenishing stocks. It's up to you how and where to utilize them. Everything's clear?}
{122}{}{Perfectly clear.}
{123}{}{Yes, and as for your question... We can produce nothing more than }
{124}{}{ product units per month specifically for your needs. Factory can't do more so far.}
{125}{}{Good. No questions left.}
{126}{}{Alright then. And now I'll pull out those damn boxes. Move aside!}
{127}{}{(Leave)}

{130}{}{A-ah, isn't it our courier... How sweet. But I'm busy, don't interrupt me.}
{131}{}{Okay.}
