{100}{}{You see a passerby.}
{101}{}{You see an ordinary Salt Lake City citizen.}
{102}{}{Sorry, I'm in a hurry.}
{103}{}{Ho, Mister Hickok! Glad to see you!}

#Наем машиниста:
{300}{}{Hi. How are you?}
{301}{}{I'm looking for a trainman. There is a long road ahead...}
{302}{}{Fine.}
{303}{}{You're nuts! No one in the city will even go near the railway station. The sheriff won't let you! If someone agrees to go with you, then certainly not from the locals. And enough of this. I don't want the hassle.}
{304}{}{It's a shame.}
