{100}{}{You see a sickly city dweller.}
{101}{}{You see a sick citizen. He got a fever, and his forehead is dripping sweat.}
{102}{}{You see a citizen. He has a fresh face and feels pretty good.}

{103}{}{Hello. What are you doing in my house?}
{104}{}{Get away! I feel so bad! O-Oh...}
{105}{}{Here's my savior! Hats off!}
{106}{}{Hey, it's okay. I'm done with these injections.}
{107}{}{I'm fine, really! Well... Thanks for the concern...}
{108}{}{Oh, thank you! I feel better already!}
{109}{}{You gave the patient an antidote, and soon he will recover.}
{110}{}{Hey, what the hell are you doing!?}
{111}{}{It will not help him.}
{112}{}{Are you out of your mind? Get away from me with that stuff!}
{113}{}{It will not help him. You need the antidote.}
{114}{}{This man is not in need of treatment.}
{115}{}{Medicines are needed}
{116}{}{The patient is exposed to dysentery. He needs medicines, using only skills is not enough here.}
{117}{}{Are you sure you know what to do?}
{118}{}{You fail the treatment.}
{119}{}{You successfully treated the patient. Now the he will be better.}
{120}{}{You see a citizen.}

#Женские реплики:
{1105}{}{Here's my savior! Hats off!}
