{100}{}{You see a citizen.}
{101}{}{You see one of many local residents.}
{102}{}{Hello}
{103}{}{Thanks for helping with the dog.}
{104}{}{ }

{110}{}{Johnny is upset again about something.}
{111}{}{It’s because of the dog.}
{112}{}{Oh, still can’t calm down?}
{113}{}{Yes, goes behind the house, looking, although she's never coming back.}
{114}{}{Very sad story.}
{115}{}{What do you think had happened to her?}
{116}{}{Surely she is digested in the stomach of that one-eyed freak from the slums.}
{117}{}{Ugh, how can you... He seems harmless.}
{118}{}{Ha! You should have seen him in action!}
{119}{}{What action?}
{120}{}{During raids, this insidious guy cooked us a soup from dog meat.}
{121}{}{Hmm, I have the impression that you just hate him.}
{122}{}{That’s right, he makes me sick.}
{123}{}{Maybe the dog just went together with the pack somewhere on the outskirts?}
{124}{}{How do I know?!}
{125}{}{Okay, don't be so irritable.}
{126}{}{Let's change the subject...}
