{100}{}{You see the sheriff.}
{101}{}{You see Burton "Whip" Hickok, the sheriff of Salt Lake City.}

{102}{}{Excuse me, what is this place?}
{103}{}{I really need to pay my attention to education in these parts, if so many people fail to read the "Sheriff" sign at the entrance...}
{104}{}{Oh, it's the sheriff's office? And you are...}
{105}{}{I'm actually the sheriff himself. My name is Burton Hickok, but people sometimes call me "Whip". And to immediately answer the next question: Yes, my ancestor is *that* Hickok. And yes, I bring order by the whip... And the gun if it's necessary.}
{106}{}{Okay, Sheriff Burton, now everything is clear to me.}

#Dialogue start:
{110}{}{So you caught the thief at the Quok brothers? You did the right thing. For a long time I've been cleaning out the city from all this dirt. But there are still bastards that are trying to turn Salt Lake into a shithole, hence we appreciate each victory of justice over lawlessness. On behalf of Salt Lake City, I express my gratitude for the help. I do not know what made you act, but I will not forget that. According to customs I should pay to you. $3000 is the amount that the traders would have lost, if it were not for you. Thanks again.}
{111}{}{Wow! That is quite a fee!}
{112}{}{Okay. Take this one to the cell, and this one we will release... [Turns to you] This is my first and last warning, only because you're the new person in town. I don't know what pushed you onto a dirty business, but we won't forgive you in the future. I'm sure you understand me. [stroking his gun] Now get out.}
{113}{}{Damn, that was really messed up...}
{114}{}{So you are that elusive ghost? Oh, we had already heard rumors about your "exploits" beforehand. I don't why you are wanted for in the whole wasteland, but if you make problems in *my* city, *I* will be the one who rids the world from you. And now relax, that was a warning, the first *and* the last.}
{115}{}{I understand, sheriff. You don't need to repeated yourself.}
{116}{}{Talk.}
{117}{}{How are things going, sheriff?}
{118}{}{I have to tell you something important.}
{119}{}{I need to get going.}
{120}{}{Really? And what is it?}
{121}{}{Nevermind, wasn't as important.}

#Question answer
{122}{}{I was able to get a filter for the artesian tower. Can you tell me who would be the best option to sell it to?}
{123}{}{Could you find an open position for a vagrant? No, not for me.}
{124}{}{Sheriff, I need some *serious* work. Well... You get what I mean.}
{125}{}{}
{126}{}{Sheriff, there is some nasty business about some dog...}
{127}{}{You know that Merck beats his wife? I can attest to it!}
{128}{}{Merck killed his wife! I saw it with my own eyes!}

#About the tower filter:
{130}{}{To me.}
{131}{}{Uh... May I ask why? I thought the Nuka-Cola factory could require one, for example.}
{132}{}{That's right. But then our city will continue to have problems with healthcare and clean water. Those who would possess the possibility to generate a lot of clean water could become a real scourge for the city and provoke a lot of conflicts.}
{133}{}{What conflicts? Between whom?}
{134}{}{For example, between the ordinary people and the factory. If the filter is in possession of the city, the factory will suffer significant income losses, which will have impact on jobs. Given that the factory is the industrial base for the city and the main local enterprise, nothing good would come of it. The worse the situation at the factory - the worse the situation of the population.}
{135}{}{Then why not to give the filter to the factory?}
{136}{}{Because the factory will seize the water supply, using it for business and not for the benefit of the population. Many would be outraged by that. I suggest to find a neutral side that would equalize the situation. I'm the sheriff - I'm that side. Sell the filter to me and there will be no big problems.}
{137}{}{And what price would you pay?}
{138}{}{Ten thousands. I can't take more out of the treasury, since we're not a rich city. The factory would certainly offer bigger amount, but I have already said how it would end. Think about it.}
{139}{}{Deal.}
{140}{}{I'll think about it and make a decision later.}
{141}{}{Well, it's up to you. But you'd better consider my words.}
{142}{}{Okay.}
{143}{}{Well, you made a wise decision. Here is your money. And... Thank you. Your assistance to our city will not be forgotten.}
{144}{}{No problem, Sheriff!}
{145}{}{You delivered a filter for the artesian tower and this significantly improved the local living conditions.}

#Cola Merchant
{146}{}{I want to report a crime! The merchant in the parking lot sold me irradiated Nuka-Cola.}
{147}{}{Damn, I could smell that something was fishy about that asshole! It never occurred to me to check his goods for radiation exposure. He probably has serious mental issues, carrying irradiated things around. Well, we have to confiscate and destroy the goods... [Calls for his sergeant and tells him to settle the matter before turning his attention back to you] Thank you for your testimony. This was a timely decision, someone could get hurt.}
{148}{}{You're welcome, Sheriff.}

#About the cleaned up Vagrant:
{150}{}{For a vagrant, huh? Is this about the one that wanders around the sales area in the center? Was about time for him to get himself from the gutter... Very well, I can think of some job for him. Not for the soft-handed though, but it will be hard and honest work. Tell him to come to me and we'll talk about it.}
{151}{}{Will do.}

#Gary Gilmore Quest:
{152}{}{There is actually something I'm not capable of doing myself, but I am not sure you would be capable either.}
{153}{}{}

{154}{}{There is actually something I'm not capable of doing myself.}
{155}{}{Tell me, it sounds interesting...}
{156}{}{First a bit of history, so you know what kind of a hole you are going to stick your nose in. Once there was a civil war in Salt Lake, and the criminal underworld thrived in it. It was a difficult time for the city. Then I decided not to stand it any longer and deal with the bastards.}
{157}{}{And?}
{158}{}{I knew the approximate number of the perps. So, I took a troop of determined boys with me and we raided all their hot spots. The captives cracked out and gave away their accomplices. As it turned out, sometimes it is useful to cross the line.}
{159}{}{And?}
{160}{}{We gathered the full gang and put them on public display in the square. The city learned the lesson well. Most scumbags hung on the gallows for three days. Those who were involved with some illegal business but did not deserve to die were cast away from the city. We haven't heard from them in a long time... Until recently.}
{161}{}{So what did they do now?}
{162}{}{We managed to nearly forget that they exist, not counting some occasional deaths on the road southwards. But over the last couple years we began to hear more and more about Provo - especially about attacks on caravans and travelers. Sometimes these attacks make no sense whatsoever. I think they are trying to take revenge on us.}
{163}{}{So they don't come to the city?}
{164}{}{They are simply too afraid to come here. But, apparently, they got bored with farming either. The gang occasionally carries out small raids and robberies in the outskirts of the city. But there is the guy who holds the whole gang together.}
{165}{}{Who is he?}
{166}{}{Gary Gilmore. The "records" of the offender are so diverse it makes you wonder. For me it is obvious that he is clearly not right in the head. He deserves to die like no other, but - and this is important to me - our city folks must witness his death.}
{167}{}{And what keeps you?}
{168}{}{A dozen thugs in the unfamiliar ruins of Provo, which is also spiked with traps throughout. We would lose a lot of men trying to assault them in there. It is much easier to slip in alone. But I need my people here, so I've been looking for a mercenary for a while, bold and experienced enough to, if not get Gilmore alive, then at least to bring him down.}
{169}{}{A serious job. Is there a serious payment involved?}
{170}{}{For our city, a bounty of 3,000 per head is pretty serious. For the living criminal I'll pay twice as much. I advise you to take the time and think carefully about everything. First evaluate the situation, then make a decision.}
{171}{}{Agreed, I will do this job.}
{172}{}{I have to think about the offer.}
{173}{}{Enough of this. I'm not a mercenary actually... [leave]}

{177}{}{Gilmore refuses to go back to Salt Lake. Maybe it's better if I just shoot him?}
{178}{}{I'll be glad of any opportunity to show the city some form of justice, but public hanging is preferable.}
{179}{}{Well, you certainly know this better.}
{180}{}{Gilmore is dead. It was the only thing that could be done.}
{181}{}{You think, I will rejoice just by receiving such messages? I need proof, strong and unambiguous. Can you present some?}
{182}{}{Here's his head. You're not going to deny that it's *his* body part, right?}
{183}{}{Unfortunately, no.}
{184}{}{Evidently. Rest assured, the city will not just take your word for it. People will whisper, make up stories... And now - get out from the office and come back only with some evidence!}
{185}{}{[Go]}
{186}{}{Excellent work! Look - so frail-looking and how much trouble he made... We will place this head on the main square, where the whole city would see and admire the inevitability of retribution. Well, as promised, here's 3000 for the job done. Thank you, we will not forget it.}
{187}{}{You're welcome.}

{188}{}{So, what about Gilmore? When is the trial?}
{189}{}{The bastard will get what he deserved, but not immediately. We still have to question him on many issues. Afterwards we'll drag him through the streets for everybody to see. And then he'll finally get what people like him should get.}
{190}{}{I see.}
{191}{}{Gary Gilmore and his life of crime is over.}
{192}{}{Excellent work! Many would envy to such grip. Well then, you are not only did a great job, but also saved life of many potential victims of that maniac. Because of this I'll gladly double the bounty. Here. [hands you $6000]}
{193}{}{Glad to help, Sheriff.}

{197}{}{Sheriff, since we dealt with the maniac, do you maybe have another job for me?}
{198}{}{So you think you are tough? Or you just like to take someone else's life for hard cash? Okay, it's not my business. I am willing to pay a bounty for every head of the rest of the Provo gang. And do not even think to deceive me - we keep a dossier on each of them, with photos and detailed descriptions.}
{199}{}{Clear. Well, I'll think about your offer. See you later.}

As for the dog #
{200}{}{As we do not have enough dog problems here... I'm listening.}
{201}{}{The boy who lives across from here lost his dog and asked me to find her, but the dog died...}
{202}{}{Let me guess - from your hands, right?}
{203}{}{Yes, but I had to do it! She had obviously caught rabies and attacked me.}
{204}{}{No, the outcast who lives near the artesian tower did it.}
{205}{}{I understand. The city always had rabid dogs. Relax, I will talk with the boy and explain the situation to him. You just stay here and wait.}
{206}{}{To be honest, I am not so sure. I should go and check.}
{207}{}{Excellent!}
{208}{}{No, I'll do it. Since it's my fault, I'd better tell him myself.}
{209}{}{Are you sure? Well, it's up to you.}
{210}{}{I talked to the kid and his family. Everything is fine. You can forget about that incident.}
{211}{}{Thank you, Sheriff!}
{212}{}{And why did he do it?}
{213}{}{Because he eats them!!!}
{214}{}{I thought so. To be honest, I am even grateful. Though we all dislike the guy, he rids the city of stray dogs. However, without direct proof I can't do anything about it.}
{215}{}{I have the tag of the dog. I found it just outside of his house.}
{216}{}{I have no proof.}
{217}{}{I have no proof, but I witnessed it myself! Is this enough?!}
{218}{}{And what should I do about it? Punish a person on someone else's words? And what if that isn't true and the dog then returns to the owners? How would I look? "The sheriff punishes the innocent!" - I disagree with such course of events.}
{219}{}{True, I then will look for evidence.}
{220}{}{Good enough for me. I'll talk to them. Relax.}

# Additional dialogue about Gilmore
{232}{}{Look, sheriff. You're a smart man. If you need someone for some "wet work", then this is your real chance. There are  }
{233}{}{ notches on my gun. Don't you think I couldn't handle a small local problem?}
{234}{}{Well, you know better.}
{235}{}{You doubt my abilities? Then I don't need your stinking job.}
{236}{}{Sheriff, I have seen a lot during my wanderings and got myself out of a lot of sticky situations. I would really like to help you.}
{237}{}{Hmm? You look pretty sharp, I don't know about the rest. Well, you decide. If you die, don't come screaming at me.}
{238}{}{Hmm, if you really are an excellent shooter, you may be able to stand up for yourself...}
{239}{}{That's great. What is this problem that needs to be solved?}
{240}{}{Sheriff, I do not advise to reject my proposal, if you need "wet work" done. I have }
{241}{}{aliens from Area 51 on my tab, for example.}

#About bikers
{250}{}{Sheriff, they say you know the whereabouts of the bikers base. Is that true?}
{251}{}{Yes, it's true. And I'm not going to share that information for nothing. First, prove your worth to this city.}
{252}{}{I could give you some cash for the information.}
{253}{}{Don't you think I've already done enough?}
{254}{}{I will consider your words.}
{255}{}{Money? Do I look like a merchant to you?  However... You can make a donation to the city. Around $3000, for instance, would help a lot around here.}
{256}{}{Done, here is my donation.}
{257}{}{Well, now I see that you are not one of those who spit on law and order. Now, concerning your problem: here are the coordinates of Battle Mountain, where one of the biker camps is located. I haven't been there myself, so all I can do is to share this information.}
{258}{}{Thank you.}
{259}{}{Hmm. Let me think. Given your reputation in my city, I... }
{260}{}{...am pleased to share the information with you.}
{261}{}{...will not help you.}

# About Merck and family problems
{262}{}{For a long time I had such suspicions but didn't find anything conclusive, and his wife doesn't tell me anything. I guess she is too afraid. Nevertheless, I can not interfere. It is their private life.}
{263}{}{Really? And when it's too late?}
{264}{}{Well, what can I do? If the wife herself admits it and asks for help... But even in that case, I do not like to punish people for someone's words. It's a small town, there are a lot of gossip and family grievances. It is better to stay away of it, believe me. Hopefully, life will teach them to appreciate each other.}
{265}{}{Hmm. Well, if you're so sure then...}
{266}{}{What?! Damn it! I suspected that it would end badly. But if I had intervened, the problem wouldn't got resolved. You can't simply change people like Merck. Now we bust his ass. Hey guys! Get ready! And you wait here until we get back.}
{267}{}{[Wait]}

{268}{}{I got the bastard! He was so hysterical that he didn't even bother to resist and asked for the gallows himself. I suppose, when he sobers up and sleep it off, he will talk differently. What do you think, what to do with him?}
{269}{}{Public hanging! An edification, so to speak.}
{270}{}{Hang him, but not in public. Let this shameful case remain a secret, as nothing could help Merck. He is condemned.}
{271}{}{He has no longer any roots in the city, maybe it is better to exile him?}
{272}{}{Sentence him to community service under high security. He needs some discipline.}
{273}{}{I do not know, it's up to you.}
{274}{}{You're right. I'll think about the punishment.}
{275}{}{Oh! Thank you for the money!}
{276}{}{Yes, you're right. He lacks discipline. It is a pity that it has come down to this, because he was a promising man. His wounded pride is his doing.}
{277}{}{Well, thank you for reporting it to me. Here's 200 bucks. I hope you will continue to abide order in Salt Lake. All the best.}
{278}{}{Banish him? I already went through this once with the bastards who are now settled in the Provo area. Now they won't ever step a foot in here. I hope Merck will also understand this lesson. }
{279}{}{I agree. This is his personal problem, let it go with him to the grave.}
{280}{}{We have not had a public execution in a long time... Well, it may be worth it to shake up the public a little and to remind everyone how it all began...}

{281}{}{Uh... Sheriff, I already took care of it. Merck is dead.}
{282}{}{Oh, that's how it is! Maybe you also want the sheriff's badge?! Turn around and leave my offices. We don't need the likes of you in our city.}
{283}{}{Uh...}

# Answers about the city
{310}{}{Anything specific?}
{311}{}{Forget it, there's another question.}
{312}{}{Thanks for your answer. Bye.}
{313}{}{More or less alright I guess.}

{350}{}{Some sneak is raiding all the Nuka-Cola vending machines around here. Everyone at the factory is in panic, and we have not a single clue who could do that.}
{351}{}{About Provo. The people still don't believe that everyone there is dead. News got by with caravan merchants, but no one from my folks wants to go in there and check. I hope the fucking bastards are dead after all.}
{352}{}{Gary Gilmore got what he deserved. May he burn in hell!}
{353}{}{Well, the Nuka-Cola factory got an unprecedented growth. Things are getting better. Though on the other hand, the better the factory works, the worse the ecology in the city because of all the produced waste. Damn unfair situation.}
{354}{}{It seems that the Nuka-Cola factory will soon fall apart. We ought to do something. Workers scatter in all directions, the production drops. However, the people are getting better, since lower emissions from the factory means less harmful substances thrown into the lake and the city becomes cleaner.}
{355}{}{We all noticed that the health matters in the city are getting better. We got way fewer diseases and there is no such crowds in front of toilets anymore. This makes me happy.}
{356}{}{Health in the city became very bad. Real plague. I advise you to beware of direct contact with people and drink cola instead of water.}
{357}{}{In general, the city is thriving. I've never seen such a flow of visitors. Apparently, in the wastelands are already spread rumors that the city got up to it's feet - and you can earn here some money and lay your head. I hope this will continue.}
{358}{}{The whole town has gone mad. I barely hold the situation together. People can get feral any moment and tear up me, or anyone else in their path, to pieces. We must do something, but there are no good ideas. I do hope we'll figure something out...}
{359}{}{The whole city lives its ordinary life. The population does not complain, everyone knows their place and somehow get along.}
{360}{}{With the situation in Provo resolved, the town is calm again. Thanks to you, the citizens calmed down and are no longer afraid to go out at night.}


#Additions about Gilmore and Provo
{370}{}{This is the batch of heads from Provo, as agreed.}
{371}{}{Well, let's look at them...}
{372}{}{[Next]}
{373}{}{What? Are you trying to mock me?}
{374}{}{Oh, come on! Just think about how it rolled on the floor...}
{375}{}{Another problem of the city solved. Thank you on behalf of all citizens. Here's your reward, }
{376}{}{ dollars.}
{377}{}{To think how much one gets for an ordinary head...}

#Reaction to the sheriff of Uranium City
{380}{}{[Catching the sight of your sheriff's badge, he raises a skeptical eyebrow] Where did you get that?}
{381}{}{I am the elected sheriff of Uranium City.}
{382}{}{Well, you see, they just gave it to me. I had no desire to take it, but they insisted...}
{383}{}{I heard something about this town from the caravaneers... They dig out uranium ore for power plants there, right? Well, it's nice to see that other settlements keep to maintain order by the law. Settle down sheriff, for you I am willing to find more time than usual.}
{384}{}{It is nice to see a friendly representative of the law. Well, let's talk, Sheriff.}
{385}{}{Mm... Well then, hide this trinket in a pocket, until I took it away. *I* am the sheriff here, and nobody except *me* will carry that title within my city.}
{386}{}{Uhm, sure, Sheriff.}

# Ghost Train
{400}{}{Are there any working trains riding through the city lately?}
{401}{}{Ha! You here for that too? Tired of the simple life? Then you better go to the gallows in the evening. More often then not, there is someone to bid this life farewell.}
{402}{}{So after all trains are coming through here, right?}
{403}{}{Yes, there is one. Comes in the middle of the night. Rushes through at half speed without stopping, vanishes heading west. They say that sometimes you can hear the soul of the driver playing harmonica. Those who saw the "Ghost Train" silhouette are afraid to cross the tracks. What if it suddenly appears out of nowhere and chop you into small pieces?}
{404}{}{Are you serious?!}
{405}{}{Quite! Some even tried to jump onto the roof of the car, but were burned by infernal flames, turning into ashes.}
{406}{}{Wow! And how often does it come through?}
{407}{}{Several times per season, heading back and forth. It clearly has a very long track. Must be in need to collect a lot of souls on the road.}
{408}{}{Uh okay, skip the horror-show... Do you know his final destination?}
{409}{}{I don't. Some believe that it does not have stops and turns. Some even swear that he can be in different places at the same time.}
{410}{}{Hmm, I have heard from the likes of them... At the bars.}
{411}{}{But it's not just all drunken nonsense. It exists. Whatever it is, it exists! Half of the city saw it.}
{412}{}{Half of the city?! Well, if you think about it, maybe there is an element of truth. Anyhow, thanks for the story, but I have to go.}
{413}{}{Sheriff, skip those children's tales. We both know that the "Ghost Train" is a real one, only slightly different from usual...}
{414}{}{Someone sometimes travels by train to the north and west. Someone had seen a robot, which is still cleaning the railway. But who needs it, and why - nobody knows.}
{415}{}{Clearly, that means it exists for real.}

#About Reaper of Souls
{450}{}{Halt! Not one step further!}
{451}{}{Sheriff? Uh... I didn't do anything!}
{452}{}{Look at this, the honesty itself stands in front of me. Answer, why do you go to the station?}
{453}{}{I've got some business there, Sheriff. But it does not concern you.}
{454}{}{And what is it?}
{455}{}{I'm going by train far beyond the city. }
{456}{}{Answer me, damn you! Answer before it's too late!}
{457}{}{Get out of my way! I will not say anything!}
{458}{}{Before it's too late? What are you talking about?!}
{459}{}{Hell, you don't understand what you're getting into! You can't stop him, even if you put against him everyone from your lousy vault.}

{460}{}{Have it your way. You *never* will tell *anything* to anybody. [Sheriff pulls out his gun]}
{461}{}{(Oops, time to mosey along...)}

{462}{}{What are you talking about?}
{463}{}{No need to act stupid, smartass. You know.}
{464}{}{The Reaper of Souls, right?}
{465}{}{We do not call his name out loud. The walls have ears.}
{466}{}{But who is he, dammit?!}
{467}{}{Listen up, stubborn. He asked me to stop you, but I don't want to interfere in other people's problems. This is my last warning - go back to your city and forget about all of it. The Reaper will not return.}
{468}{}{Heh, I knew it, sheriff. You're just his houseboy!}
{469}{}{How do you know this?}
{470}{}{The Reaper seeks out pure souls since a long time ago. I do not know why.}
{471}{}{Uh ... "pure souls"? Looks more like a horror story for kids.}
{472}{}{Ha-ha-ha! The Sheriff believes in scary stories! That's hilarious!}
{473}{}{"Pure Souls"? You mean humans that where not subjected to mutations, am I right?}
{474}{}{He needs the descendants of those who survived the Great War in safe vaults, which preserved their purity. Our city has nothing he desires.}
{475}{}{What happened in your town?}
{476}{}{Why would he need genetically pure bodies?}
{477}{}{Why did he abduct people?}
{478}{}{During the War the people of Salt Lake survived thanks to family shelters. People came out of them gradually, over decades. So, over time, people here have lost their purity.}
{479}{}{Hmm. Apparently, the local ecology in combination with radiation and mutations affected genetics of population.}
{480}{}{Well, of course. You've got quite a cesspool here. What else should one expect?}
{481}{}{Yea, this city is not really considered clean...}

{482}{}{I do not know what he does with the abducted, but they do not come back.}
{483}{}{Why not finish off this viper once and for all?}
{484}{}{We have to reckon with his power. He is not just a human, he's a miracle of genetic mutations combined with bionics. He is even capable to read your mind.}
{485}{}{Are you seriously saying there is no way to stop him?}
{486}{}{Not in your case. So I warn you for the last time: turn around and go away. The survival of this city is more important to me than your stupid mission.}
{487}{}{Like hell! I will go to the station, whether you want it or not.}
{488}{}{Okay, I'm going back to the city... For now...}
{489}{}{You're wrong. The Reaper of Souls will continue to rampage throughout the wastes. You don't even know his goals. What will happen if he finds "pure soul"?}
{490}{}{I'm sorry, but I *have* to stop you. [The Sheriff pulls out his gun]}
{491}{}{(Oops, time to mosey along...)}
{492}{}{I don't know, and don't even want to. Now turn around and don't come back.}
{493}{}{Hold on, Sheriff! Maybe he's trying to create an army of soldiers to seize the whole wasteland? Your city has already suffered enough, it's time to end this!}
{494}{}{Don't fool yourself! What could *you* do against him?! What?!}
{495}{}{I'm not so easily intimidated, I've already met him. Believe me, he has to have a weakness and I'm going to find it.}
{496}{}{You are so naive it dazzles me. Even I had to make a deal with him, in order to save Salt Lake, I had no choice whatsoever. Everyone has to pay the price sooner or later in their life. You'll understand that in a while.}
{497}{}{This is a difficult confession to make. But the city is getting up on its feet, and the Reaper of Souls will continue to leech it until it's dry.}
{498}{}{And how are you going to catch up to him? He moves on a black bullet-train. You can not even trace the path he takes.}
{499}{}{I have the coordinates of the vault he stationed in. He has the Overseer from my city taken, who has a tracking device on. I can pinpoint the train's whereabouts. Besides, I already have working transport and good weapons. The surprise element is on my side, along with my wits and courage. I am fully prepared for it, sheriff!}
{500}{}{I see you are serious... I'm afraid this decision will haunt me for the rest of my life. Go.}
{501}{}{I will not let you down, Sheriff!}
{502}{}{...And I will not let my city to be put in danger by trusting a wimp like you. Don't make me laugh and get out, for all of our sakes!}
{503}{}{The path is clear!}
{504}{}{I won't warn you twice.}

#Reaper dead
{505}{}{The Reaper of Souls is dead!}
{506}{}{Dead? I can't believe it... I guess we'll see that in the meantime.}
{507}{}{So what was the deal you concluded with him?}
{508}{}{Once the city had very unstable social conditions. Criminal vermin flooded the city, even during the day no one felt safe. It was practically a civil war. Then he came, offered help in bringing order. It wasn't an easy decision for me to make.}
{509}{}{What did he demand in return?}
{510}{}{Pure souls. As much as he wanted. At first he demanded them twice a year, then more and more often.}
{511}{}{And you did not try to resist?}
{512}{}{My men have always been in fear of the Reaper of Souls. They could not resist him.}
{513}{}{That decision was so immoral that I will execute judgment upon you by myself. RIGHT NOW!}
{514}{}{Don't blame yourself. Such decision was better than long and bloody struggle with the criminal underworld.}
{515}{}{You're right, one must pay for everything in the end, the simple truth of life.}

# Women's replica:
{1112}{}{Okay. Take this one to the cell, and this one we will release... [Turns to you] This is my first and last warning, only because you're the new person in town. I don't know what pushed you onto a dirty business, but we won't forgive you in the future. I'm sure you understand me. [stroking his gun] Now get out.}
{1128}{}{Merck killed his wife! I saw it with my own eyes!}
{1173}{}{Enough of this. I'm not a mercenary actually ... [leave]}
{1184}{}{Evidently. Rest assured, the city will not just take your word for it. People will whisper, make up stories... And now - get from the office and come back only with some evidence!}
{1193}{}{Glad to help, Sheriff.}
{1198}{}{So you think you are tough? Or you just like to take someone else's life for hard cash? Okay, it's not my business. I am willing to pay a bounty for every head of the rest of the Provo gang. And do not even think to deceive me - we keep a dossier on each of them, with photos and detailed descriptions.}
{1208}{}{No, I'll do it. Since it's my fault, I'd better tell him myself.}
{1215}{}{I have the dog tag. I found it just outside of his house.}
{1236}{}{Sheriff, I have seen a lot during my wanderings and got myself out of a lot of sticky situations. I would really like to help you.}
{1253}{}{Don't you think that I have already tried?}
{1410}{}{Hmm, I have heard from them at the bar...}
{1451}{}{Sheriff? Uh... I didn't do anything!}
{1463}{}{No need to act stupid, clever girl. You know.}
{1467}{}{Listen up, stubborn. He asked me to stop you, but I don't want to interfere in other people's problems. This is my last warning - go back to your city and forget about all of it. The Reaper will not return.}
{1468}{}{Heh, I knew it, sheriff. You're just his houseboy!}
{1494}{}{Don't fool yourself! What could you do against him?! What?!}
{1513}{}{That decision was so immoral that I will execute judgment upon you by myself. RIGHT NOW!}