{100}{}{You see Beagle.}
{101}{}{You see the sheriff's senior assistant.}

{102}{}{If you came to sheriff, he's gone on business.}

{110}{}{What issue brought you here? If you came to sheriff, he's in his office.}
{111}{}{God, who's this?! Maybe, we should just shoot it?}
{112}{}{You did the right thing regarding that thief! Good job!}
{113}{}{Provo should have been eradicated long ago!}
{114}{}{About Gilmore - good job!}
{115}{}{Weapon in holster! Now!}
