{100}{}{Vending machine is out of order.}
{101}{}{}
{102}{}{You won't get much with your bare hands from this vending machine.}
{103}{}{It's empty}
{104}{}{You've already robbed this vending machine and hoarded all change.}
{105}{}{Can't do anything with this.}
{106}{}{Good thinking, but you can't manually break the register of this solid machine.}
{107}{}{You managed to pick the lock and open the back cover of the machine. Now you've got all the change!}
{108}{}{Yes!}
{109}{}{You weren't able to pick the lock.}
{110}{}{You were able to open the back cover using tools. Now you've got all the change!}
{111}{}{You got }
{112}{}{ bucks.}
