{100}{}{Not in combat!}
{101}{}{You are looking doubtfully upwards - to where the water drips, and the sky is barely visible through the small windows. The spiral staircase goes into darkness, and you can't see the end of it. It's a hell of an artesian tower! The ascent to its apex would take a lot of energy.}
{102}{}{I'll fall powerless if I won't rest.}
{103}{}{Climb up, risking your health.}
{104}{}{Exit.}

{105}{}{Ugh! What a view! Is Salt Lake really this dirty?!}
{106}{}{You are on top of the broken artesian tower. A stunning panorama view opens from here.}
{107}{}{Panoramic view from the top of the tower temporarily sharpens your perception.}
