{100}{}{You see an empty newspaper vending machine.}
{101}{}{You see a newspaper vending machine, inside of which lies something.}
{102}{}{Nothing here.}
{103}{}{There is something inside, but the cover is stuck too tightly to open it with your bare hands.}

{104}{}{You didn't swung hard enough and failed to remove the cover.}
{105}{}{You swung hard enough and was able to dislodge the cover.}
{106}{}{Done}
{107}{}{Using the tools you unscrewed the cover.}
{108}{}{Done}
{109}{}{Using the master key you picked the lock on the cover.}
{110}{}{Done}
{111}{}{Alas, you could not open the lock.}
{112}{}{Alas, you cannot open the lid.}
{113}{}{In this case it does not help.}
{114}{}{Useless}
{115}{}{It's no use - the lid is already open.}
{116}{}{You find 50 bucks and take them for yourself.}
{117}{}{It's amazing how there is still money in here...}