{100}{}{You see cisterns.}
{101}{}{You see large tanks with a smelly concoction that will soon become Nuka-Cola.}
{102}{}{You committed a dangerous act of sabotage at the Nuka-Cola factory.}
{103}{}{Nuka-Cola factory has suffered a diversion! Not without your help.}

{104}{}{This liquid has already been poisoned, re-injection will do nothing.}
{105}{}{You have poisoned the tank with the liquid, but it's not enough. Poison another one.}
{106}{}{You see large tanks with a smelly concoction that could be Nuka-Cola, if you haven’t poisoned it.}
{107}{}{You've already poisoned enough liquid, do not waste the poison in vain.}
{108}{}{Done!}
{109}{}{This one is done}
