{103}{}{Not during combat!}

{110}{}{Here you are able to conduct your trading transactions for the purchase and distribution of Nuka-Cola.}
{111}{}{Buy a new batch of Cola.}
{112}{}{Unload Nuka-Cola from you backpack to the warehouse.}
{113}{}{Take Nuka-Cola from the warehouse.}
{114}{}{Take a look on how many bottles are left in stock.}
{115}{}{Leave.}

{120}{}{Currently no items in your stock.}
{121}{}{Currently left in stock (}
{122}{}{) bottles of your Nuka-Cola.}
{123}{}{Back.}
{124}{}{Leave.}
{125}{}{There is none of your products left in the warehouse.}

#Покупка колы
{130}{}{You exceeded your limit for this month. Wait until the plant will manufacture the next batch of goods for you.}
{131}{}{This month you can buy no more than }
{132}{}{ bottles of cola.}
{133}{}{Buy 4,000 bottles (cost $8,000).}
{134}{}{Buy 3000 bottles (cost $6000).}
{135}{}{Buy 2,000 bottles (cost $4000).}
{136}{}{Buy 1000 bottles (cost $2000).}
{137}{}{Buy 500 bottles (cost $1,000).}
{138}{}{Buy 100 bottles (cost $200).}
{139}{}{You have applied to the warehouse and obtained the required number of bottles at wholesale price. The cola is placed in the warehouse.}

#Загрузить колу
{140}{}{Move cola to container.}
{141}{}{5 bottles.}
{142}{}{10 bottles.}
{143}{}{20 bottles.}
{144}{}{30 bottles.}
{145}{}{50 bottles.}
{146}{}{100 bottles.}
{147}{}{Move all bottles.}
{148}{}{Leave.}
{149}{}{Done.}

#Выгрузить колу
{150}{}{Left at the warehouse (}
{151}{}{) bottles of cola.}
{152}{}{}
{153}{}{Take 5 bottles.}
{154}{}{Take 10 bottles.}
{155}{}{Take 20 bottles.}
{156}{}{Take 30 bottles.}
{157}{}{Take 50 bottles.}
{158}{}{Take 100 bottles.}
{159}{}{Take all the bottles.}
{160}{}{Leave.}
{161}{}{Done.}
{162}{}{There is nothing left in the warehouse.}
{163}{}{Sorry, you can’t carry so much.}
{164}{}{Take everything I can carry.}
