#! Not used in 1.0
{100}{}{This is hatch.}
{101}{}{A powerful door with a powerful lock. You can only open it by a specific key.}
{102}{}{It's locked. You can only open it with a specific key.}
{103}{}{Locked, need a key}
{104}{}{This door will stand even in front of a small nuclear explosion. Joke. Ha-ha.}

{110}{}{You unlock this huge hatch.}
{111}{}{Ready!}
{112}{}{This is useless here.}
{113}{}{The door is already open.}
{114}{}{Useless}
{115}{}{It will not help. Look for the key.}