{100}{}{You see a door.}
{101}{}{You see a very powerful door with a heavy lock. Even a dynamite won’t take this!}

{102}{}{The door is locked.}
{103}{}{Here it does not help. You need a key.}
{104}{}{The door is already open}
{105}{}{You open this mighty door.}

{106}{}{Hey, you! Get out of there!}
{107}{}{What the hell is -- a thief! I'll show you!}
{108}{}{Hey! Don't go there. Don't even think about!}
{109}{}{Haa! Bad work, thieving scum!}
