{100}{}{}
{101}{}{Hey! Go be crazy somewhere in the wasteland, you fucking psycho!}
{102}{}{Hey! What are you doing!? Get away from there before I throw you in a cell!}
{103}{}{You were caught in the act of vandalism. This will hardly make a positive impact on your reputation in the city.}

{104}{}{This street light is not working.}
{105}{}{You shortened the wires, causing the light in the lamp go out.}
{106}{}{If you were a technician, you would understand what to do.}
{107}{}{You smashed the bulb in a street lamp with a stone like a hooligan.}

#Жен реплики
{1101}{}{Hey! Go be crazy somewhere in the wasteland, you psychotic bitch!}
