{100}{}{You see a beggar.}
{101}{}{You see a disgraced old man digging through scraps. He looks like he's seen some rough times.}

{102}{}{You're just a pair of cunt flaps waving in the breeze. Get the fuck away from me.}
{103}{}{I don't need anybody's help!}

#Floating Dialogue
{109}{}{ }
{110}{}{I saw the way you looked at me! Don't you fucking dare look down on me, you sack of shit!}
{111}{}{Fuck off, old man.}
{112}{}{Shut up! You're nothing! I was here before your daddy was alive!}
{113}{}{And just look at what you've accomplished. Inspiring!}
{114}{}{Fucking kids! Oh, back in my day, let me tell you...}
{115}{}{...when dinosaurs roamed the earth...}
{116}{}{...the mayor put everyone in their place. Shit like you, we'd have sent to Golgotha!}
{117}{}{Those days are long gone, old man.}
{118}{}{I was a man once! And now I'm living on the streets, digging through trash, and you - what are you?!}
{119}{}{Ha-ha-ha!}
{120}{}{You're laughing in the face of death!}
{121}{}{Took the words right out of my mouth, you old fossil!}