{100}{}{You see the pursuer.}
{101}{}{You see a brutal-looking thug. He looks like a man on a mission.}
{102}{}{This pursuit is over.}

{110}{}{Hey, Deveraux! Why are you running from us?}
{111}{}{Weren't we good to you? Weren't we real nice?}
{112}{}{Stryker appreciated you. Protected you. Don't you remember?}
{113}{}{And then you stabbed him in the back. Not good, Deveraux. Dirty move.}
{114}{}{You want to come out and talk about it like adults?}
{115}{}{Talk about this? Or about your friend, the one you sold to another gang?}
{116}{}{That was a mistake, Terry. We get that.}
{117}{}{You can still play this smart. You can still go back.}
{118}{}{It'll be like nothing ever happened!}
{119}{}{...as long as it doesn't happen again.}
{120}{}{We'll even let your friends go! I swear on my mother's life!}
{121}{}{What do you say, Deveraux? You want to do this the easy way?}
{122}{}{::waits::}
{123}{}{::sneers::}
{124}{}{Have it your way, Deveraux! We'll do it the hard way!}
{125}{}{Get the fuck out here, you little bitch!}
{126}{}{If you don't come out, we'll shoot that place full of more holes than my daddy's condom!}
{127}{}{...fuck it. Lay it on him, boys!}
