{100}{}{You see Nick Hauer.}
{101}{}{You see a man in dark sunglasses and a duster that looks like it's a lot of trips across the desert.}
{102}{}{They're close...}
{103}{}{Thank you, friend. We couldn't have done this without you.}
{104}{}{Thanks for the help. We'll bury the dead and head off to San Francisco. This is gonna be a tough one to forget.}
{105}{}{What? What's he saying, Terry?}

{110}{}{Stop! You hear that?}
{111}{}{They're hot on our trail. This is going to hell.}
{112}{}{Dammit! Deveraux's family slowed us down. We've got no choice, friend. We'll can't slip away in this moonlight without being seen. Got any ideas?}
{113}{}{That thing will go up like a candle. You run, I'll hold them off.}
{114}{}{If we make a stand in that house, we might just make it.}
{115}{}{Still playing the hero, huh, friend? Well, good luck - it'd be a terrible waste for a man like you to die for strangers.}
{116}{}{Just go. There isn't much time.}
{117}{}{I can handle myself. You just focus on keeping them safe.}
{118}{}{You're right. This is gonna be a shitty night.}
{119}{}{Let's go!}

#Female version
{1103}{}{Thank you, friend. We couldn't have done this without you.}
{1115}{}{Still playing the hero, huh, friend? Well, good luck - it'd be a terrible waste for a woman like you to die for strangers.}