{100}{}{You see a townsperson.}
{101}{}{You see a rather sketchy looking man.}

{110}{}{[He hurriedly pulls you along] Just, just move along...me and my friend have important things to discuss.}
{111}{}{You can calm down, I'll give you both the chemist and his friend. But in return, I want you to put in a good word for me with Stryker.}
{112}{}{Right, you're in the way of some important things. I'll pay 1000 dollars for both of you to disappear.}
{113}{}{I know why you're here. Here's my offer - either you get out, now, or me and Mr. Thompson will take care of you.}
{114}{}{You need to leave. Now!}
{115}{}{Fine, I'm going.}

{116}{}{Good choice. Lead the way, we'll be right after you.}
{117}{}{Ugh, I didn't want to get swept up in this shit anyway. Hand over the money and we'll leave.}
{118}{}{Thompson's at the hotel already? Shit, I didn't sign up for this, we're going.}
{119}{}{Oh really?}
{120}{}{I'm serious. Uh... Deveraux cooked up a bomb and will blow the whole building to hell. And don't think he won't do it - the man's desperate! You shouldn't have backed him into a corner!}
{121}{}{Damn, I knew he was crazy. Listen, you wanna run? That's your problem. You'll still get caught. I'm not going to die for this.}
{122}{}{Good.}
{123}{}{Here's the cash.}
{124}{}{You two have to get the hell out of here, now. Stryker's got a new plan and you're about to fuck it all up. I shouldn't even be telling you this! Move it!}
{125}{}{Damn it, Stryker and his secrets... Don't worry, we won't interfere.}
{126}{}{Go.}