{100}{}{You see a child}
{101}{}{You see a child. Unwashed, smelly and angry at the world.}
{102}{}{[Glares sullenly at father]}

#Talking to kids (male PC)
{110}{}{I don't talk to strangers, asshole!}
{111}{}{Get away from me!}
{112}{}{Dad! This man's touching me!}
{113}{}{Don't come closer!}
{114}{}{I won't go!}
{115}{}{I don't know you.}

#Talking to kids (female PC)
{120}{}{I don't talk to strangers, bitch!}
{121}{}{Get away from me!}
{122}{}{Dad! This woman's touching me!}
{123}{}{Don't come closer!}
{124}{}{I won't go!}
{125}{}{I don't know you.}

#Patrick's package
{130}{}{Get lost!}
{131}{}{My pleasure, right after you tell me where Patrick's package is.}
{132}{}{Another word and I'm calling my dad!}
{133}{}{Look, I won't hurt you. Honest. I just want to know where the letter is. Can you tell me that?}
{134}{}{I... Can't tell... [he looks over at his father nervously]}
{135}{}{Your father took it? You don't have to say anything, just nod.}
{136}{}{[The kid looks at his father to make sure he isn't watching, then slowly gives a small nod.]}
{137}{}{Okay. You can relax now.}

{138}{}{Talk, you little shit! Whatever you're afraid of, you should be more afraid of me!}
{139}{}{Did your dad take it from you? Start talking! [smack him across the head] Out with it!}

{140}{}{Your cruel treatment of a child has negatively affected your karma.}

#Concert posters
#! Achtung! This text is used for many kids across Reno
{150}{}{Yes?}
{151}{}{You want a job? I'll give you 10 dollars to put up these posters.}
{152}{}{Nothing.}
{153}{}{Cool! I'm gonna buy myself a hot sandwich!}
{154}{}{Here's the money and the posters. Put them where everyone can see them!}
{155}{}{Wait.}
{156}{}{You have no posters left.}
{157}{}{Will do!}
{158}{}{Good.}

#Female version
{1150}{}{Yes?}
{1157}{}{Will do!}