{100}{}{You see a bodyguard.}
{101}{}{You see a grim bodyguard. He's looks very dedicated to his job.}

{102}{}{Z-z-Z-z-Z...}
{103}{}{It's best not to disturb him.}

{110}{}{Put away your weapons!}
{111}{}{I repeat - put away your weapons!!}
{112}{}{An assassin! Protect Mr. Bertolini!}
{113}{}{Thief!}

{120}{}{We don't want junkies here! Get out!}
{121}{}{Don't even think of doing anything to the boss - I'm watching.}
{122}{}{The boss thinks a lot of you. He's a good judge of character.}
{123}{}{The boss only accepts visitors during the day.}

{130}{}{[The bodyguard jerks awake at the sound of your footsteps] Hold it! No visitors at night. Get out! Office hours start at eight in the morning.}
{131}{}{[Attack!]}
{132}{}{[Leave.]}