#Барабанщик
{100}{}{You see Jay.}
{101}{}{You see Jay Nilsson, black inhabitant of the streets. People call him "Potato foot".}
{102}{}{Hey, let's show these crackers some rhythm!}
{103}{}{I'll miss your vocals.}

{110}{}{[At first, it looks like a pile of garbage has come to life. Soon, a person's dirty foot emerges from the trash, followed by an equally dirty face, covered with wild black hair. The figure shuffles up to some massive metal cans and sits down.]}
{111}{}{Uh, what are you planning?}
{112}{}{Huh? I'm going to play. Sit back and listen.}
{113}{}{Are you serious?}
{114}{}{Damn right! You see? [he holds up two chipped, mismatched sticks] Drum sticks. I found them in the trash. Want me to play something?}
{115}{}{Okay, I'm curious.}

{116}{}{Hey, no. [he holds up a hand] Not on an empty stomach.}
{117}{}{Here's ten dollars.}
{118}{}{What?! You want me to feed you so you can bang on some cans?}
{119}{}{Sorry, I've got nothing.}

{120}{}{Respect! Alright, we're cracking. One, two, three, four... Let's go! [he starts skillfully banging out a melody on the cans]}
{121}{}{Whoa-whoa-whoa, my ears! That's not music, that's noise! Knock that off!}
{122}{}{I can feel the rhythm! Keep it up!}
{123}{}{I don't know if that was worth it. I'm just going to go now.}

{124}{}{[Jay continues to practice on his "drum" set.]}
{125}{}{Have you been doing this long?}
{126}{}{I won't bother you.}
{127}{}{Ever since childhood. I give people a show, make a few bucks, live another day.}
{128}{}{You know, you're way too good to be playing on trash cans. I'm putting together a band for the local club. Interested?}
{129}{}{A band?! Wow! I'll go there right now!}
{130}{}{Go on, then.}

{131}{}{I'll play you a few tunes if you help me get something to eat. I'm starving to death here.}