{100}{}{You see a Reno local.}
{101}{}{You see a simple citizen of the slums.}

{109}{}{Err, hello. We're always happy to see guests, but...}
{110}{}{Err, hello. We're always happy to see guests... Unlike our neighbors...}
{111}{}{Your neighbors don't talk much...}
{112}{}{Goodbye.}
{113}{}{Exactly. They weren't like that all the time. But since Mark disappeared, it seems they're getting ready for "payback".}
{114}{}{Uh, "payback"?}
{115}{}{Mister Wright doesn't like people who let him down. Mark did. Now somebody has to pay, understand? I pity the old geezers, but they are gonna die soon anyway.}
{116}{}{What happened to Mark?}
{117}{}{Well... I think I heard something about that, but I can't really remember anymore... Maybe you have something to refresh my memory... If you catch my drift.}
{118}{}{Of course, I understand. Would 100 bucks be enough?}
{119}{}{Do you know who I am or who my boss is? I think it's best if you don't. Let's just say he gets information out of people much more quickly than me.}
{120}{}{I know one trick I can perform on your fingers that might help. Want to find out?}
{121}{}{How much? Why not...}
{122}{}{Here's the cash.}
{123}{}{Oh, thank you sir. [he sticks the money into a pocket] It's good that you came to see us.}
{124}{}{Now, what did you hear?}
{125}{}{It was late at night. Mark returned all thin, wounded and covered in road dust. He had an argument with his family, we listened through the wall... They wanted Mark to run away somewhere up north. Shit, that's exactly what he did, left his own family, damn coward! All because something happened when doing a job for Mr. Wright and he couldn't finish what he started. Yeah, pretty tough luck.}
{126}{}{Thank you for the info. I've gotta go now. Oh, and this talk never happened.}
{127}{}{Turns out Mark ran away up north.}
{128}{}{Oh, I understand... Err, I'll be happy to help your boss... Any way I can. No problem.}
{129}{}{W-wait... I'll be glad to help.}
{130}{}{Don't make me laugh. Do you know who owns these slums? I'm talking about Wright, Mister Wright. He would like us to keep turning him a profit, so you can keep your tricks to yourself.}
{131}{}{You were lucky this time.}

#Женские реплики
{1123}{}{Oh, thank you ma'am. [he sticks the money into a pocket] It's good that you came to see us.}