{100}{}{You see Patrick.}
{101}{}{You see Patrick, neat and clean as always.}
{102}{}{The spectators scatter in terror!}
{103}{}{Watch them, not me.}
{104}{}{All this effort, for nothing...}
{105}{}{Thank you for your help.}

#On loading map
{110}{}{Most of the people are here. The rest should turn up while I begin the speech.}
{111}{}{Got it. What do you need from me?}
{112}{}{You'll be my bodyguard. Although, that was probably too pompous... Anyway, your job is to provide security. No doubt someone here is an assassin or a protester. We need to make sure that everybody can enjoy the show without being hurt.}
{113}{}{Don't you think you are too suspicious? No one here is looking like threat.}
{114}{}{Alright. You go read your speech, I'll keep a close...-er eye on the crowd.}
{115}{}{Alright, I'll keep an eye out. Maybe even two.}
{116}{}{Let's pray everything goes to plan.}

#Πεχό
{200}{}{Ahem... [adjusts collar]}
{201}{}{Anyway, let's begin...}
{202}{}{We are gathered here, guided by the hand of God.}
{203}{}{Led through a helpless, doomed world.}
{204}{}{We are all victims of greed and ruthlessness of our ancestors.}
{205}{}{When, due to a shortage of resources, man turned to war...}
{206}{}{...the Great War.}
{207}{}{Since then, nothing has changed. People continue to destroy the last bit of humanity within themselves.}
{208}{}{Forgetting that we are all brothers and sisters. All are... God's children.}
{209}{}{This film will tell us how it all happened, so that we avoid the mistakes of our past.}
{210}{}{Well, let's begin!}