{100}{}{You see a prostitute.}

#Подробное описание
{110}{}{You see a lady of the evening. Her tattered clothes are draped seductively around her body.}
{111}{}{You see a prostitute. She winks at you.}
{112}{}{You see a prostitute. Her eyes are like blown fuses.}
{113}{}{You see a prostitute. She smells like flowers.}
{114}{}{You see a prostitute. She smells like mother.}
{115}{}{You see a prostitute. Her breasts look ready to pop out of her tattered rags.}
{116}{}{You see a prostitute. She looks as if she kills her mates and eats them.}
{117}{}{You see a prostitute. She is appraising you like a jeweler.}
{118}{}{You see a prostitute. Her tattered clothes are draped seductively around her body.}

#Ответные реплики
{197}{}{Get out of here! I'm not even allowed to look at you!}
{198}{}{Forget it! I don't serve junkies.}
{199}{}{You interested? Lesbian stuff is cheaper.}

{200}{}{I’m called Easy. And you?}
{201}{}{Want some company?}
{202}{}{Let me teach you something only a woman can teach.}
{203}{}{Do you want me to warm your bed?}
{204}{}{You need a hole?}
{205}{}{Looking for a girlfriend?}
{206}{}{If you've never had a Reno girl, you've never known true love.}
{207}{}{Looking for action?}
{208}{}{How about a REAL woman in your bed for a change?}
{209}{}{I feel so empty inside, baby, can you help me?}
{210}{}{You look glum. You want me to cheer you up?}
{211}{}{Forget the casino. I can show you a REAL thrill!}
{212}{}{You wanna dance?}
{213}{}{Looking for a girlfriend for the night? Or for ten minutes?}
{214}{}{I know what you need.}
{215}{}{You getting hot under the collar? Or somewhere else?}
{216}{}{You wanna get down to business?}
{217}{}{Wanna spend some quality time?}
{218}{}{We can talk afterwards...but that costs extra.}
{219}{}{Missionary, cowgirl, doggy-style, oral, anal, bondage, S&M, gang-bang - anything you want. Just try me.}
{220}{}{Come on, time is money.}
{221}{}{You want me? Pay first...}
