{100}{}{You see strong man.}
{101}{}{You see strong man out for your blood!}
{102}{}{You see strong woman.}
{103}{}{You see strong woman out for your blood!}

{110}{}{You won!}
{111}{}{You won! It feels awesome!}
{112}{}{You defeated a formidable opponent. What a rush!}
{113}{}{You defeated an extremely dangerous opponent. You're on top of the world!}
{114}{}{You got the achievement, "Legend of the New Reno ring".}
{115}{}{You got the achievement: "Legend of the Las Vegas ring".}
{116}{}{Surviving so many grueling fights has increased your endurance.}