{100}{}{You see Michael the bartender.}
{101}{}{This is Michael. His name is written on a worn-out badge on his shirt.}

{102}{}{Want a drink before the fight?}
{103}{}{Speaking of fights, can I place a bet?}
{104}{}{Speaking of fights, can I participate?}
{105}{}{Sure, show me what you've got.}
{106}{}{Nope, I'm going to go.}
{107}{}{That's it?}
{108}{}{Another question.}
{109}{}{Bye.}

{110}{}{We've got a guy for that. He accepts bets right before the fights start, see him then.}
{111}{}{I doubt it... But anyway, it's not up to me. Take the hall on your right into the gym, then head up to the boss's office. Talk to him.}
{112}{}{Who's in the ring right now?}
{113}{}{Hell if I know. Some tribals from the wastes. They're brought in from time to time by slavers. They're replaced so quickly, I don't even try to remember their names. And why should I? They're just meat. [he shrugs indifferently]}
{114}{}{I'm looking for the girl in this picture. Ever seen her around here?}
{115}{}{Nope, don't think I have, but her body seems familiar... Weird, how could a body be familiar? [he screws up his face, scratching his head] Maybe from the night club? Oh yeah! I'm not really sure, but I think I saw her dancing there. A body like that... [he looks like he's about to start drooling]}

{116}{}{I heard you had a guy running dope here. I really need some, you dig?}
{117}{}{Are you okay? What dealers?!}
{118}{}{These dealers. [show note]}
{119}{}{Hm... You're right. Jackson must have screwed up.}
{120}{}{Ah, yeah, I heard something like that. Shady guys, made some deals before leaving. But Mr. Bishop kicked them all out.}
{121}{}{Got it.}

{122}{}{Good to see you, champion.}

#Female version:
{1102}{}{Want a drink before the fights, friendo?}
{1122}{}{Good to see you, champion.}