{100}{}{You see Mark.}
{101}{}{You see your old pal, prospector Mark. He's back in Reno.}
{102}{}{You have acquired the metal detector via the long, hard, but honest way.}

{103}{}{Thank you for everything you've done for us!}
{104}{}{Someone killed Wright! Must have been one desperate bastard. He's done us all a great favor.}
{105}{}{Hey, how are things? I'm still holding on, but this can't go on forever...}
