{100}{}{You see a militiaman.}
{101}{}{You see a member of Thompson's assault team. He is waiting for your instructions.}
{102}{}{Stay alert! These scum could be anywhere.}

{110}{}{What do you got for us?}
{111}{}{The surveillance system is down. You can move in.}
{112}{}{What do you need, again?}
{113}{}{Nothing yet. I'm working on a diversion.}
{114}{}{We need you to put an end to their surveillance system before we can get to work.}
{115}{}{Okay.}
{116}{}{Finally! Time to clean up these rats! If you've got the guts, we'd be happy to have you. If not, go back to Mr. Thompson and tell him we've taken care of things.}
{117}{}{I'm with you! I wouldn't miss this fight for the world!}
{118}{}{My work here is done. You'll have to do this without me.}

{119}{}{I like your attitude. Let's put these punks in their place!}
{120}{}{[Begin the assault]}
{121}{}{Then stay out of our way. It's time for the real men to get to work.}
{122}{}{[Go to Thompson's headquarters.]}
{123}{}{Wait, I changed my mind. I want to help you fight.}

#Женские реплики
{1123}{}{Wait, I changed my mind. I want to help you fight.}