{100}{}{You see a representative.}
{101}{}{You see a serious-looking man sent on another's behalf.}
{102}{}{We're done here.}

{103}{}{Who are you?}
{104}{}{I represent Mr. Thompson. We know about your deal with Stryker's gang and wish to present a counter-offer.}
{105}{}{I know about your arrangement with Stryker. I suggest you to reconsider.}
{106}{}{I'm here to prevent your business with Stryker. Permanently. [Attack]}

{107}{}{I like my terms with Stryker. Why should I switch?}
{108}{}{Stryker is dead. His gang can't do it without him. The fact that I even got to you is proof they don't know what they're doing.}
{109}{}{Because Thompson's going to win this war, very soon. When he does, he'll take control of all the drug dealers. Do you really think one chemist on Stryker's side is going to make a difference?}
{110}{}{You make a good case. Alright, I'm in. Tell Thompson to send someone to hash out the details.}
{111}{}{Good. I hope you're not planning on playing both sides...}
{112}{}{Really?}
{113}{}{Just a warning, that's all. I'm leaving.}
{114}{}{You do this, and Mr. Thompson won't forget it. Trust me, he's a much more fearsome enemy than Stryker. One chemist on Stryker's side won't give him the strength to protect you.}
{115}{}{Uh... Well, Thompson's just way cooler than Stryker, don't you think?}
{116}{}{This is childish. Leave.}
{117}{}{Well, I warned you.}

#Женские реплики
{1106}{}{I'm here to prevent your business with Stryker. Permanently. [Attack]}
{1113}{}{Just a warning, that's all. I'm leaving.}
{1117}{}{Well, I warned you.}
