{100}{}{You see a strongbox.}
{101}{}{You see a reinforced safe with a code lock.}
{102}{}{The safe withstood your blows. It will withstand many more.}
{103}{}{Locked!}

{105}{}{You've already cracked this safe.}
{106}{}{This might be harder than you thought.}
{107}{}{Got it!}
{108}{}{Wrong lockpicks.}

{109}{}{You successfully crack the lock on the safe.}
{110}{}{You couldn't open the safe.}
{111}{}{With ease, you punch in Huey's code and the lock pops open.}
{112}{}{Open!}