{100}{}{You pull the balaclava over your head.}
{101}{}{You pull the balaclava off your head.}
{102}{}{The balaclava is off your head.}
{103}{}{Your balaclava is in your bag because it is incompatible with your other currently equipped items.}
{104}{}{You cannot put on the balaclava. It is incompatible with your other equipped items.}
{105}{}{Your balaclava won't be very convincing while you're wearing a Luciano ranch security jacket.}
{106}{}{That mask doesn't fool me! I know who you are!}
{107}{}{You've caused a ruckus with one of the casino's Tommy guns. Luciano will be pleased.}