{100}{}{You see tracking monitors.}
{101}{}{You see tracking monitors with access to the local database.}

{111}{}{[Look for information on Mr. Mordino]}
{112}{}{[Finish.]}
{113}{}{You find transcripts of decisions regarding Mr. Mordino and his hotel. They weren't in his favor.}
{114}{}{You can't figure out how to do that.}
{115}{}{[Look for information about a planned deal]}
{116}{}{You find notes on a secret meeting between Stryker and Wind of War. Stryker will trade chems from his lab in exchange for weapons, armor, and ammunition. Exchanges will take place on the second floor of the Silver Legacy hotel. Stryker's men have already booked a room and tightened up security.}
{117}{}{This explains a lot...}
{118}{}{[Disable the tracking system and change the password]}
{119}{}{[Done]}
{120}{}{Now what's left is to tell the assault team that they can start the operation.}

{121}{}{[Copy the accounting ledgers.]}
{122}{}{You copy the accounting details. These will be very useful for Luciano's administrator.}
{123}{}{[Back]}