{100}{}{You see a computer.}
{101}{}{This computer still works! It must have been in standby mode for decades.}

{110}{}{The terminal contains administrative information and provides access to the radio station.}
{111}{}{[Contact the bikers using the details written on the piece of paper Jay Kukish left to you.]}
{112}{}{[Leave.]}

{120}{}{What the hell!? Who is this? Copy?}
{121}{}{This is Jay Kukish.}
{122}{}{I'm just a wanderer, looking for Jay Kukish. I need to talk to him.}
{123}{}{Jay! Long time no see. I was told you went up north and disappeared. Listen, we're meeting up near Hawthorne, in a small town called Bridgeport. You know, the one filled with rednecks. Come by and tell us what you found. Where are you now?}
{124}{}{In New Reno.}
{125}{}{What? Huh... [long pause] ...Your voice sounds pretty weird, Jay... Okay, who is this?! Hey! Answer me! [you cut the feed]}
{126}{}{Hmm, so they don't even know what Jay Kukish is doing. Why didn't he return to them after vault 8? I should go to Bridgeport and talk to these bikers face to face. Let's hope they're friendly.}
{127}{}{[The voice pauses] No shit? We haven't seen Jay in a while. How do you know him?}
{128}{}{He betrayed and robbed my people. I'm going to kill him and take back what's mine.}
{129}{}{I'm not sure. Either he saved me, or the other way around. Anyway, I need to talk to him.}
{130}{}{I think we're friends, otherwise he wouldn't have left me a jacket, pistol, and contact details.}
{131}{}{Yeah? Well, I won't get in your way, then. Jay disappeared a few months ago. We've heard a lot of rumors since then... Listen, we need to talk in person. We're in a small town called Bridgeport. If you really need to see Jay, you'll come. That's all I can say. Over.}
{132}{}{Bridgeport... Alright. Over.}
{133}{}{Big question mark, huh? That's Jay alright. Listen, I can't help you for now. Probably, you should come, tell us what you know. We're in a small town called Bridgeport. If you really need to see Jay, you'll come. That's all I can say. Over.}
{134}{}{I don't know if I can trust you. Maybe Jay's already dead in a ditch somewhere, and you're just trying to get our trust... We need to talk in person. We're in a small town called Bridgeport. If you really need to see Jay, you'll come. That's all I can say. Over.}

#Information about the bunker
{160}{}{[Look for information about this bunker.]}
{161}{}{This structure is located under the town square. Its construction was contracted by the mayor's office, paid with taxpayers' money. It was intended to serve as a mass shelter in the case of bombings near Reno.}
{162}{}{[Next]}
{163}{}{The bunker was filled by most of the town's population in October 2077. In time of panic and gang war some families used it to hide and wait through the dangerous times. Eventually, bunker was abandoned.}
{164}{}{[Back]}

#Female version
{1122}{}{I'm just a wanderer, looking for Jay Kukish. I need to talk to him.}
{1129}{}{I'm not sure. Either he saved me, or the other way around. Anyway, I need to talk to him.}