{100}{}{This switchboard seems to control power to the entire second floor of the casino.}

#Ремонт
{101}{}{The electrical panel's cover is closed with a padlock.}
{102}{}{There's a lot of current running through these wires. You probably shouldn't touch them with your bare hands.}
{103}{}{The second floor's lighting has been turned off.}
{104}{}{The second floor's lighting has been turned on.}
{105}{}{You can stand here all day, but this panel won't open itself.}

#Взлом
{110}{}{The lock is broken already.}
{111}{}{The lock holds strong against you.}
{112}{}{You easily break the lock.}
{113}{}{This keyhole lock is closed.}
{114}{}{Locked by key.}
{115}{}{The lock is open.}
{116}{}{You have unlocked the lock.}
