{100}{}{You see a slot machine.}
{101}{}{You see a slot machine with flashing lights.}
{102}{}{This slot machine is currently occupied.}
{103}{}{You get nothing from the machine.}
{104}{}{This machine is in working order.}
{105}{}{Nothing.}
{106}{}{An ordinary slot machine, the same as every other one in this room.}

{107}{}{You inspect the machine and find the reason behind high loss rate: someone misaligned the spinners, reducing the chances of a win.}
{108}{}{This explains everything!}