{100}{}{You probably shouldn't touch anything. Especially not that big red button... Or that other one.}
{101}{}{You can't use this in combat.}
{102}{}{This console has no further uses.}

{104}{}{You see a radio transmission control terminal. It looks like the guards use the radio to communicate, but you find some other commands on the console.}
{105}{}{[Use your computing skills to deactivate all the slave collars]}
{106}{}{[Activate the self-destruct on all the collars]}
{107}{}{[Leave]}
{108}{}{You can't figure out how to do this.}
{109}{}{Command initiated}
{110}{}{[Exit]}
{111}{}{[Try and deactivate the system using your technical skills]}
{112}{}{The control system is deactivated.}
{113}{}{[End]}
{114}{}{You just can't figure out this technology.}
{115}{}{[Back]}