{100}{}{You see a shabby poster.}
{101}{}{You see a beat-up old poster. There's an odd lump in the center protruding from the wall.}
{102}{}{This poster is a relic. You don't think its owner would like to see you damage it.}
{103}{}{Under the poster, you find a safe full of valuables.}
{104}{}{Wow, there's a lot in here!}
{105}{}{I'm just curious about the movie.}
{106}{}{A classic drama about a gangster with principles. In the post-nuclear wasteland, it just seems naive.}