{100}{}{You see an air vent.}
{101}{}{You see an air ventilation system. It's out of order, which isn't too surprising.}
{102}{}{You see an air ventilation system. Surprisingly enough, it still works.}
{103}{}{You hear the equipment hums to life, but one of the fans still doesn't spin.}
{104}{}{Busted.}
{105}{}{This vent is working correctly.}

#Repair attempts (skill or tools)
{106}{}{You aren't skilled enough to fix this problem.}
{107}{}{I can't do this.}
{108}{}{You already fixed the system. You don't need to do it twice.}
{109}{}{If it's not broken, don't fix it!}
{110}{}{You fixed the vents.}
{111}{}{Done!}