{100}{}{You see Rico.}
{101}{}{You see a muscular bouncer named Rico.}

{102}{}{Don't interfere. This doesn't concern you.}
{103}{}{::nods respectfully::}
{104}{}{We need more people like you around here.}

{110}{}{You looking for problems in my house?}
{111}{}{Yes, and I found one. Now I'm going to solve it.}
{112}{}{I have to see that guy.}
{113}{}{Just popping in to say hi. See you later.}

{120}{}{[Cracks his knuckles] Now you're asked for it.}
{121}{}{Wait, wait, I'm sorry! It won't happen again!}
{122}{}{Wait, I just wanted to see that guy!}
{123}{}{Bring it, you sack of meat!}

{124}{}{[Exhales slowly through his nostrils] It's your lucky day. Next time, you'll be pissing blood.}
{125}{}{Eee...}

{126}{}{This shit again? You'd better get the fuck out of here. This is your last warning.}
{127}{}{Okay, okay, I get it.}
{128}{}{That's it. Your ass is mine!}
{129}{}{Come and get it.}

{130}{}{You're not allowed there. If you want to see the prisoner, talk to Gerlach.}
{131}{}{I go where I want. Back off before I get pissed off.}
{132}{}{Gerlach said I could see him.}
{133}{}{Okay, I'll go see your boss.}

{134}{}{[He mutters something under his breath] ...fine. Don't try anything funny in there.}
{135}{}{Of course!}

{136}{}{Fix the pump first. You can see the prisoner once you're done.}
{137}{}{You should think about being nicer to me. You don't have daddy Gerlach watching out for you anymore.}
{138}{}{Fine, but I'll be back.}

#Женские реплики
{1127}{}{Okay, okay, I get it.}
{1129}{}{Come and get it.}
