{100}{}{You see a water tank.}
{101}{}{You see a water tank. By the echo inside, you can tell it's not full.}
{102}{}{You see a water tank. It has plenty of water, but judging from the smell, the water is not suitable for drinking.}
{103}{}{It looks like this basement was built to contain only one person.}
{104}{}{This village have been abandoned. The only thing left here is the desert wind.}
{105}{}{You see a tank. You hear the sound of water splashing inside.}
{106}{}{There's no point. This water is poisoned.}
{107}{}{The water is already poisoned.}
{108}{}{This should be enough for the whole settlement. Come back later to see the results.}
{109}{}{The water is poisoned.}
{110}{}{Why do you need this?}
