{100}{}{You see Derry.}
{101}{}{You see Bruce Derry, leader of the bikers.}
{102}{}{Your message about the situation in Hawthorne had caused quite a stir. Apparently, soon the bikers will leave Bridgeport, to the delight of rednecks.}
{103}{}{Piss off}
{104}{}{Hello}

{110}{}{What is it?}
{111}{}{Nothing.}

{112}{}{I'm looking for Jay Kukish.}
{113}{}{You won’t find him here. He went mad and ran off to Hawthorne.}
{114}{}{Why are you so calm while telling me this?}
{115}{}{Because our gang and Jay has a special kind of relationships. He is a lone wolf, all by himself. If you have business with him - go ahead, find him. As for me, I'm more worried about what we all are supposed to do now. He made some hussle in Hawthorne, we answered his call, gathered here - and now we are still sitting, with no effect.}
{116}{}{So you're all waiting for some special news from Hawthorne?}
{117}{}{Why did Jay need to go to Hawthorne?}
{118}{}{The garrison in Hawthorne got jacked - its automated defense systems are no longer working. Time to pay a visit there.}
{119}{}{Tell me about yourself. How did you join a biker gang?}
{120}{}{Tell me about your gang.}
{121}{}{Bye.}

{122}{}{Well, yeah. We could smell something's changing. Jay have been spreading the rumors that it's better to stay close to Hawthorne, that something is going to happen there. So, we gathered in Bridgeport - considering that to stay in Hawthorne itself is dangerous.}
{123}{}{Jay said he became interested in a governmental vault. According to him, it is located somewhere in Nevada. Therefore, Jay decided to look for the coordinates on a military base.}
{124}{}{Oh really? Somehow, Jay haven’t contacted us yet, to tell about it. We've been waiting this news for quite a long time. Also, frankly speaking, the rednecks here are beginning to get on our nerves. We'll move to the base as soon as everyone is ready.}
{125}{}{I am a veteran of the Civil War in Reno. Then, local entrepreneurs used to get bikers involved into their shady dealings. We fought as a strike force, as mercenaries, until the situation came to the level when we were not needed anymore. Then we realized that we've just been used. So, we decided to spit in the face of the whole city. I wanted to be free.}
{126}{}{Here you'll see people who failed to fit into the current society. Look at Bigfoot - he's a Wind of War veteran. When he realized that the local military was worse than the raiders, he abandoned them, to live by his own principles. And here's Whiner - his settlement has been destroyed by raiders. He had no choice, but to seek revenge. Our gang helped him, and then - gave him new purpose to live.}
