{100}{}{}
{101}{}{}
{102}{}{This is in working order.}
{103}{}{You cannot do that in combat.}
{104}{}{Why would you do that?}
{105}{}{Right idea, but wrong timing. Somewhere in the electrical circuit a link is missing.}
{106}{}{This doesn't need repairs.}
{107}{}{You have shamefully failed to turn on the generator.}
{108}{}{You turn on the generator. As expected, it works great. Now all that remains is to deal with the external power grid.}
{109}{}{You have directed the current to a street transformer.}
{110}{}{You are unable to rewire the generator to send the current where it is necessary.}
{111}{}{The street transformer now works and directs energy to homes. It remains to make sure whether or not the electricity is supplied properly.}
{112}{}{You have failed to achieve the desired result.}

{113}{}{This house is now provided with electricity.}
{114}{}{You have failed to connect the power to the house.}
{115}{}{This hardly helps here.}
