{101}{}{The books, pamphlets and writing on these shelves may tell more about the history of Bridgeport.}
{102}{}{You cannot read in combat.}
{103}{}{With your education it would be too difficult and utterly boring to dig in such a large quantity of papers.}
{104}{}{A greater understanding of scientific principles are required to use this computer.}
{105}{}{You will need not only your hands, but the also your head, to examine publications on these shelves.}

{110}{}{These shelves are completely lined with a variety of pre-war pamphlets and books, as well as the personal records of the last owner. In general, these materials cover the history of Bridgeport.}
{111}{}{Read the section on the pre-war history of the settlement.}
{112}{}{Read the section on the year 2077.}
{113}{}{Read the section on the postwar history of the settlement.}
{114}{}{Leave.}

{115}{}{It was a small town, inhabited mainly by two types of citizens - rich families and spa workers. Bridgeport was famous for its mountain resorts, including lakes filled with trout and pristine snowy slopes. A quiet place, almost a paradise, a place for a carefree life. Partly because of this a number of well-off citizens of Nevada and California made their vacation homes here for various holidays and weekends.}
{116}{}{Judging from the scraps of information, during the Great War, the village was completely wiped out due to radiation. Local residents had nowhere to shelter from radiation, brought by winds from the destroyed nuclear explosions of Los Angeles to the south and Zone 51 in the north-east. Realizing their doomed situation, many residents had arranged a celebration right on the streets of the city as a farewell to life, choosing to face death with with a smile on their face.}
{117}{}{The village has probably been uninhabited since the day when the population was wiped out in 2077. Less than ten years ago, the first settlers returned life to this village - the refugees from Reno.}