{100}{}{You see Betty.}
{101}{}{You see the usual horned cattle. And, apparently, the only one in this settlement.}

{110}{}{Mo-o-o.}
{111}{}{[Lead the brahmin]}
{112}{}{[Leave the brahmin here]}
{113}{}{[Do nothing]}

{114}{}{Moo!}
{115}{}{That's better.}
{116}{}{Moo?}

{117}{}{[Mine brahmin with Dynamite]}
{118}{}{[Mine brahmin with Plastic explosives]}
{119}{}{You're free, Betty. Mutants are dead and I don't need you anymore.}
{120}{}{Betty's free now.}

{121}{}{(This is not a suitable place for bait)}
{122}{}{You lured the mutants into a trap and blew the mine.}
{123}{}{Brahmin abuts and refuses to go further.}
{124}{}{Move your ass you fucking animal!}

#Попытка толкать (фразы при низкой карме)
{130}{}{Move, stupid fat cattle!}
{131}{}{Well, move yourself, animal!}
{132}{}{Go forward or 'll smack you with a whip!}
{133}{}{Should you continue to balk - you'll get what you deserve!}
{134}{}{You're making me mad you animal. O-oh, how mad I am!}
{135}{}{Hrm, stupid brahmin...}
{136}{}{You'll soon get some for your stubbornness!}
{137}{}{Alright, one last time and my patience will shatter}
{138}{}{Move!}
{139}{}{Come on, Betty, dear, move... Or I'll BLOW YOUR BRAINS AWAY!}