{100}{}{You see Joseph.}
{101}{}{You see the administrator of the miners guild.}

{110}{}{Thanks, you gave me hope, Sheriff!}
{111}{}{Thanks, you gave me hope!}
{112}{}{[You see the guild administrator; he looks prettier and cleaned up] Oh, look who we got here!! That's really the one, who I'm always glad to see. I take this opportunity to sincerely thank you for giving me the chance to return to a normal life. You give us hope for the future. Not often such things happen in our lives. Thank you very much.}
{113}{}{You're welcome.}
{114}{}{Well, I'm going to restore order in the office. There's just an awful mess...}
{115}{}{Bye.}
{116}{}{Oh, by the way, there is a weapon of the previous administrator in the safe. You can take it - think of it as a little reward for your efforts.}
