{100}{}{You see a closet with arsenal.}
{101}{}{You see a basic wardrobe, equipped for the storage of firearms.}

{102}{}{The mistress won't like it if someone will be digging in here without permission.}
{103}{}{Well, well, well, would you like to ask me first, m?}
{104}{}{Next time you try something without permission - you'll get your ass kicked}
{105}{}{Well, I've had enough!}

{106}{}{You delivered the administrator of the guild to the destination using your car.}
{107}{}{You delivered the operator to the destination using your car.}
{108}{}{You delivered the guild supplier to the destination using your car.}