{100}{}{Choosing a song, you press a button in anticipation. But in response you hear only a slight static hiss from the speaker.}
{101}{}{Choosing a song, you press a button in anticipation. With a a crackle, the music player starts up.}
{102}{}{The machine does not require a repair.}
{103}{}{Repair failed.}
{104}{}{You have uploaded new songs to the machine.}
{105}{}{Because of your incompetence, wires were fused and chips burned out. Obviously, the music player cannot be repaired now.}
{106}{}{This machine is burnt out and cannot be repaired.}
{107}{}{This machine doesn't work.}
{108}{}{You can't upload new songs, because music player doesn't work.}
{109}{}{Done}