{100}{}{}


{110}{}{I wonder how they'd be in a salad...}

{111}{}{Better exterminate them before they start talking!}

{112}{}{Note to self, only weed the ones with teeth...}

{113}{}{One less mouth.}

{114}{}{Who crossed a dandelion with a deathclaw?}

{115}{}{Rooting out weeds? Well, at least it's better than killing rats with a shovel.}

{116}{}{Kill a plant, save a fly!}

{117}{}{Was that mutated hemp?}

{118}{}{How do you like that?}


{119}{}{That should do it!}

{120}{}{Boy, was that boring, but I did it!}

{121}{}{Boy, was that boring, but I did it!}

{122}{}{You've killed all the killer plants in this field.}


{150}{}{You've killed }

{151}{}{ out of 5 plants.}
