{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging from the markings, its responsibility is the station's lights.}

{102}{}{The generator was damaged by an exploded generator at the side. For a repair you will need to replace certain parts.}
{103}{}{Parts missing}
{104}{}{The generator is functional an powers the station.}
{105}{}{This generator is in working order}
{106}{}{This generator need parts, not fuel.}
{107}{}{Useless}
{108}{}{This won’t help here.}
{109}{}{Done}
{110}{}{You replace the damaged parts. The generator is in working condition.}
{111}{}{Without some part replacement, the generator won’t work.}
