{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging from the markings, it's responsible for central equipment power supply.}

{102}{}{Seems like the ants damaged this generator, but it still can be repaired.}
{103}{}{Repair is needed}
{104}{}{}
{105}{}{The generator is operational and supplies power to the station.}
{106}{}{No use}
{107}{}{The generator is running and does not require repair.}
{108}{}{You've repaired the generator. Now it powers the server.}
{109}{}{Done}
{110}{}{This won't be any good here. The generator needs repair.}
{111}{}{You fail to repair the generator.}
