{100}{}{You see a computer.}
{101}{}{You see a computer of repair and technical services. It coordinates the work of the force fields.}

#Диалог
{110}{}{This computer controls the force fields and doors on this level of the hangar.}
{111}{}{Get access to all doors on this level of the hangar.}
{112}{}{Control force fields.}
{113}{}{[Leave the computer]}

{114}{}{Done.}

{120}{}{Force field disabled by automatic fire safety systems. From this terminal you can change the current protocol of the force fields.}
{121}{}{From this terminal you can change the current protocol of the force fields.}
{122}{}{Restore the force fields.}

{127}{}{Set the mode of the force fields.}
{128}{}{Apparently, there are two field modes. Cold mode does not allow objects to pass through the force field. Thermal mode forms the basis for the unusual heat. It is probably very dangerous.}
{129}{}{Set cold mode.}
{130}{}{Set thermal mode.}
{131}{}{Done. Cold mode selected.}
{132}{}{Done. Thermal mode selected.}
