{100}{}{You see: a control panel.}
{101}{}{Before you is the door control panel.}
{102}{}{The security system only allows you to have one surface access door open at a time.}
{103}{}{You cannot do that in combat!}
{104}{}{The door is already open.}
{105}{}{Wait, where is your holodisk?!}
{106}{}{You must gather your party before venturing forth.}
{107}{}{The Overseer won't open the vault door until you have completed your mission.}
{108}{}{You must wait for your team.}
