{100}{}{You see: Moreau.}
{101}{}{You see Richard Moreau, the head doctor of Vault 8.}
{102}{}{Hurry up with the data, we'll talk later.}

{110}{}{[You see Dr. Moreau. He looks angry.] Finally. I was thinking about sending a guard after you.}
{111}{}{That's not necessary. Why are you so upset?}
{112}{}{What?.. Forget it. Back to the task at hand: you already know that we are going outside. I can't exactly tell what awaits us out there, so be prepared for the worst. If we move swiftly and act together, everything should go nicely.}
{113}{}{What's our mission?}
{114}{}{We've recently lost radio contact with our surveillance monitors on the surface. Still, they should be recording data to a local backup. Your mission is to get a copy of those recordings manually, if that is still possible.}
{115}{}{How would I do that?}
{116}{}{Take this empty holodisk. You'll see a slot for it on the monitor. Just plug it in and press "copy". The monitor will take care of the rest - that is, if it still works. Now give me your sensor. I'll mark the monitors' positions on your map, so it could be easier for you to find them.}
{117}{}{Okay, doctor Moreau, we're ready to go. Follow me.}
{118}{}{Understood. I'll tell you when we're ready to leave.}
{119}{}{Yes?}

{120}{}{When the team is ready, type the activation code into the access panel. And don't lose the holodisk!}
{121}{}{Fine.}
{122}{}{I'll tell you when we're ready to leave.}

{123}{}{Wait, what are the rest of you going to do?}
{124}{}{I'm responsible for medical assistance, in case someone needs it. The guard will provide security. The other citizen will gather surface data with his portable monitor.}
{125}{}{Doctor, are you sure you're alright? You look stressed...}
{126}{}{You'd better keep your mouth shut. The Overseer gave you an order - that's all you should worry about right now.}
{127}{}{}
{128}{}{}
{129}{}{Look, I can't go! Maybe I’ll just go back inside?}
{130}{}{We can't go without you. It's too risky.}
{131}{}{It's too risky to go at all! It can't be a coincidence that all the monitors stopped sending data at once. Who knows what's going on out there!?}
{132}{}{Hmm... It might be for the best if you don't go. You could compromise the mission. Go back in the vault. I'll find someone to replace you.}
{133}{}{Whew, thank you. You just saved my ass... [Abandon your mission]}
{134}{}{No... No, wait. I think I just needed to let that out. I'll go outside, I can do it. You can count on me.}
