{100}{}{You see: rocks.}
{101}{}{You see many fallen rocks. They look unsteady. Climbing over them would be too dangerous. You have to find a way to move them.}
{102}{}{These rocks are too heavy to move with bare hands. You'll need some kind of lever.}

{110}{}{Your set the lever and strain. You manage to roll the smaller boulders a couple of feet, before your arms give out.}
{111}{}{*Hn-ngg...*}
{112}{}{You throw your body weight onto the lever and shift some medium-sized rocks. You've almost cleared enough space to pass.}
{113}{}{*HH-HHRGG!*}
{114}{}{Using the sign as an Archimedes lever, you slowly shift the largest boulders until they roll over the edge, crashing onto the ledge below.}
{115}{}{Whew!}
