{100}{}{You see: a terminal.}
{101}{}{You see an emergency medical terminal.}
{102}{}{You cannot do that in combat!}
{103}{}{Your science skill is not enough to break into this terminal.}
{104}{}{Accessing this computer will require a more scientific approach.}
{105}{}{Science skill needed}
{106}{}{You already broke into this computer.}
{107}{}{Nothing interesting}
{108}{}{You hacked the emergency terminal to dispense one stimpak.}
{109}{}{Yes!}
