{100}{}{You see a bored visitor.}
{101}{}{You see a visitor with a sad look.}

{110}{}{Hello. You missed the booze too?}
{111}{}{Maybe. What are you doing here?}
{112}{}{Why you have such a sour look?}
{113}{}{Yeah, why do you care?}
{114}{}{No, I was just passing by.}

{115}{}{Well, I thought maybe you would join my company, but if you don't want to...}
{116}{}{Oh, this. Of course, here's 5 bucks for a beer.}
{117}{}{Not this time.}
{118}{}{Let me think... Hmm... Oh well, I guess I'm just sad and have no one to drink with.}
{119}{}{I see. Well, I won't keep you.}
{120}{}{Trying to drink and forget about everything and everyone, don't you see?}
{121}{}{Let me get you a drink. Hey bartender, here's 10 bucks for a beer for my friend!}
{122}{}{Here is a beer, help yourself.}
{123}{}{Then let me get you a beer from my supply.}
{124}{}{Well, then have a beer from my supply.}

{125}{}{Thanks, buddy. Nice to see such friendly people in this place.}
{126}{}{Why are you so sad?}
{127}{}{You could at least try to look happy.}
{128}{}{Sorry, just sad. Sometimes I come here to honor the memory of my best friend.}
{129}{}{What happened to him?}
{130}{}{He was quite the athlete, moved by the idea of a healthy lifestyle! Day by day he trained hard, wore clean clothes and even brushed his teeth.}
{131}{}{Must been a nice guy.}
{132}{}{Why? Didn't he got anything else to do?}
{133}{}{Well, it would be all nice if one day he didn't read the poster with the pre-war advertising. It said that the use of radium water is good for the body. Here it is. [gives you a small bottle with clear liquid] He found a whole box of this abomination and started to drink 3 bottles a day... Until he died from toxic poisoning.}
{134}{}{How sad and strange...}
{135}{}{What an absurd death!}
{136}{}{Yes, it is. It turned out that radium water is toxic - slow acting poison. Oh, poor Byers, who would have known that people before the were was so stupid...}
{137}{}{It's a sad story, friend. I'm sorry.}
{138}{}{Yeah, just a large crowd of idiots. Damn right!}
{139}{}{Let's drink for the deceased, that is all we can do now.}
{140}{}{Sure, let's drink!}
{141}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. You're a good person.}
{142}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. Don't know what you have in mind, but I like you.}
{143}{}{Yeah, bye.}

#Жен реплики
{1110}{}{Hello. You missed the booze too?}
{1114}{}{No, I was just passing by.}
{1115}{}{Well, I thought maybe you would join my company, but if you don't want to...}
{1125}{}{Thanks, girl. Nice to see such friendly people in this place.}
{1141}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. You're a good person.}
{1142}{}{Okay, I probably tired you. Thank you for listening. And for the beer too. Don't know what you have in mind, but I like you.}