{100}{}{You see that cop.}
{101}{}{You see a familiar cop.}
{102}{}{Take the weapon away, before the patrol saw you.}
{103}{}{I knew you can’t be trusted. Just give me a reason - I’ll shoot you right here.}
{104}{}{I asked you - don't talk to me! If someone sees us together, we are both finished!}
{105}{}{Glad to see you in the Clean City! Have a good time, pal.}
{106}{}{Welcome to Clean City! Have a good time.}
{107}{}{The crowd on the streets didn’t expect to see this in the center of the city...}
{108}{}{Something happened...}

#Ñäà÷à êâåñòà
{110}{}{Welcome! Glad to see you and yes, I know about the outcome. Now the city will be better, thanks to you. Thank you.}
{111}{}{You’re welcome, it was fun...}
{112}{}{Wait, I thought, how can I reward you. Here, take this super stimpak. It may save your life in tough situation. Thank you once again.}
{113}{}{Thank you too.}

#Æåí ğåïëèêè
{1105}{}{Glad to see you in the Clean City! Have a good time, gal.}
