{100}{}{You see Phil!}
{101}{}{You see... That same biker from Battle Mountain! What is he doing here?}

{109}{}{Well? Havenít decided either to go or not yet?}

#Õ‡˜‡ÎÓ ‰Ë‡ÎÓ„‡
{110}{}{Hello, friend! What, not accepted by your own?}
{111}{}{Long story. I think, they wonít be happy to see me here from now on, thatís for sure.}
{112}{}{And I have been tossed out of here right away. Well I didnít started anything. Too bad. I just wanted a little tour around the vault. Why are your people so stingy? I didnít ask for much and offered payment... Ah, fuck it.}
{113}{}{Where are you heading now?}
{114}{}{I donít know yet. We are preparing for big trouble north of the base. So I have to travel on business. I can give you a ride, if you want.}

#ŒÚÔ‡‚Í‡ ‚ „ÓÓ‰
{115}{}{Ahh, perhaps no, Iíll get there myself. Take care!}
{116}{}{To Salt Lake City then!}
{117}{}{To New Reno then!}
{118}{}{Then drop me off near Lovelock.}
{119}{}{Can you take me back, to Battle Mountain?}
{120}{}{Can you drop me off near the Wind of War?}
{121}{}{Let's ride to Las Vegas, shall we?!}

#Female character:
{1109}{}{Well? Havenít decided either to go or not yet?}
{1110}{}{Hello, friend! What, not accepted by your own?}
{1115}{}{Ahh, perhaps no, Iíll get there myself. Take care!}
