{100}{}{You see a lively man.}
{101}{}{You see a thin young man in striped shirt.}
{102}{}{Thank you very much}

#ƒË‡ÎÓ„
{110}{}{(You see a thin young man, wearily digging through the grass. He wears striped shirt, that, together with long untidy hair, makes him stand out from the crowd.)}
{111}{}{Looking for something?}
{112}{}{Huh? Oh... The Kings are at it again. They took away my glasses and threw them somewhere into the grass. Iíve been looking for them for an hour already. Probably I'll have no luck without a metal detector... Ugh, it seems itís not my day. I better go to the cafe. Perhaps, I will hear something more interesting there... Oh, if you find the glasses - please return them to me. I will be the most thankful.}
{113}{}{Here they are, no need to look.}
{114}{}{[Leave]}

{115}{}{Hi. Have you seen my glasses? That would be great.}
{116}{}{Yes, your glasses have been found.}
{117}{}{No, not yet.}
{118}{}{Oh! That's fortunate. Give them to me... It's good, they didnít break. Thank you so much.}
{119}{}{Just gratitude is not enough. Pay me for the find.}
{120}{}{Youíre welcome.}
{121}{}{Is that so?.. And you made such a good impression. Fine, here's five bucks. No more.}
{122}{}{Not much more to be expected from you. Bye.}
