{100}{}{You see a poor man.}
{101}{}{You see a slum dwellers. He almost lost hope, but still holding.}
{102}{}{Hello}

{110}{}{Hello. [coughs] Just came by or you’re here for a reason?}
{111}{}{Not quite. I just want to know, how is the life in these slums.}
{112}{}{Just passing through. So I better get out of here.}

{113}{}{It's shitty, as you can see. This is not the Clean City - we have no electricity, no water, the house crumbles as we speak. I don’t know, how long we can hold in such conditions.}
{114}{}{What is this place? Some hostel?}
{115}{}{Anyone in charge here in the slums?}
{116}{}{Why Clean City flourishes, while you live in such conditions?}
{117}{}{Tell me about the Kings.}
{118}{}{That is all, I wanted to know. Bye.}

{119}{}{Yeah, something like that. Of course, no one will tolerate just anyone in here, but we don’t have strict demands either. People don’t stay for long anyway - they just die, other get away as far as possible.}
{120}{}{Well, we, of course, have an intendant. But he’s more for show. In reality the kings run the slums.}
{121}{}{Because they have money and power. And we have nothing. They didn’t made their city so clean and fixed with their own hands, but with slavery! And the likes of us they use as cheap labor force. After all, it’s impossible to find a job in the city, you have to work almost for nothing, and the Clean City takes advantage of it. Greedy and arrogant.}
{122}{}{These bandits don’t play around. If they told to do something, then make sure you do it with a smile. Perhaps, you will find them in other regions, they are all over the periphery. But they aren’t just a gang. They watch over everything, they get water, food, hold off other gangs, when they must. In return we must work for them. The weak are food for the strong, that’s what they say.}
