{100}{}{You see a gambler.}
{101}{}{You see a gambler, excitedly waving his hands to the beat of running geckos.}

#Кричат во время бегов гекко
{110}{}{Come on! Come on!}
{111}{}{Bring me the money, geckos!}
{112}{}{Toki, forward!}
{113}{}{Please! Please!}
{114}{}{Damn!}
{115}{}{Go!}
{116}{}{What a race!}
{117}{}{Will this one win?!}
{118}{}{What?! Red is leading?!}
{119}{}{Too slow!}
{120}{}{Too fast!}
