{100}{}{You see a City Hall employee.}
{101}{}{It's one of the City Hall employees.}
{102}{}{I don't deal with such issues.}
{103}{}{If you have any complains, address it to the doorknob over there.}

#Случайные плавающие фразы
{110}{}{Dull pencils again.}
{111}{}{Is the salary coming soon?}
{112}{}{I will buy myself a bulletproof vest next time I get paid.}
{113}{}{What to read? Oh, the tax declaration!}
{114}{}{Boring.}
{115}{}{With this data...}
{116}{}{Well, this is not to me.}
{117}{}{I'll never make so much money.}
{118}{}{Reports, reports, reports...}
{119}{}{Who to yell at?}
{120}{}{Not so perspective, as it seems.}
{121}{}{Another stupid idea.}
{122}{}{Junk!}
{123}{}{Another stupid answer.}
{124}{}{When is the planning session?}
{125}{}{When is the launch break?}
{126}{}{Is it dinner soon?}
{127}{}{I want to sleep.}
{128}{}{I need to rest.}
{129}{}{My eyes are tired.}
{130}{}{Read all this? Fire me.}
{131}{}{Please, just don't fire me.}
