{100}{}{You see: a watchful guard.}
{101}{}{You see a guard keenly peering up and down the street.}
{102}{}{Donít even try that again!}

#–‡Á„Ó‚Ó
{110}{}{Yes, citizen? Do you need something?}
{111}{}{Why are you looking around like that?}
{112}{}{No, nothing.}

{113}{}{In that case, don't distract me. Oh, and stay vigilant!}
{114}{}{Er... Fine, as you say.}
{115}{}{I'm watching the streets for signs of trouble.}
{116}{}{Why, has something happened?}
{117}{}{Must be a tough job.}
{118}{}{Do you see a lot of crime around here?}
{119}{}{That seems excessive. Is something going on?}
{120}{}{Iíll leave you alone.}

{121}{}{Not yet, citizen. Don't worry.}
{122}{}{Uh... Yes, as you can see.}
{123}{}{Excluding some past events, the city is completely crime free. Don't worry, citizen.}
{124}{}{I can't share that information with common citizens. Crimes and accidents are handled by a special commission.}
{125}{}{Can I be a part of that commission?}
{126}{}{Hmm... No, they wouldn't take you in. But you could still help with an ongoing investigation.}
{127}{}{Okay. A couple of citizens are acting suspicious. Their jobs require them to leave the city perimeter. When they return, they act... Strangely. Suspiciously strangely. If you really want to help, follow them and tell me, what they're doing.}
{128}{}{[Nods] I'm glad you take our city's security seriously.}
{129}{}{}
{130}{}{}
{131}{}{}
{132}{}{No, I donít want to spy on anybody.}

{133}{}{Of course. Forget everything I said.}
{134}{}{Wait, I changed my mind. What about those citizens? How are they suspicious?}
{135}{}{Fine.}

{136}{}{}
{137}{}{Who are they?}
{138}{}{How often do they go outside the perimeter?}
{139}{}{How much time do they spend outside the city?}
{140}{}{What do they do outside the city?}
{141}{}{Iíll come back when I learn something.}

{142}{}{They are citizen Jacob and citizen Emily. They work at the technical service department.}
{143}{}{They are tasked with checking the security systems around the perimeter twice a day.}
{144}{}{They used to spend around two hours, but recently, theyíve been taking much longer.}
{145}{}{They check the security systems around the perimeter. A complete check should take around two hours.}

{146}{}{I'll help with the investigation. Who knows, it may be my last chance to help the city before I leave.}
{147}{}{What's with all the rules? Look, you're wound tight due to all this bureaucracy. Just tell me what to do and I'll take care of it.}
{148}{}{That's great and all, but Iím interested in something else.}
{149}{}{No way. I think youíre forgetting who needs help here. Iíll let you dwell on it for a little while.}
{200}{}{Youíre the one who caught those two citizens breaking regulations? Good job!}
{201}{}{What will happen to them?}
{202}{}{Iíll think about it.}
{203}{}{That's up to the commission, but they'll probably be sentenced to extended isolation.}
{204}{}{Okay. Well, I wonít take any more of your time.}

{205}{}{I heard that youíre responsible for catching those two! Good job!}
{206}{}{Any news?}
{207}{}{False alarm. Everything is fine.}
{208}{}{Are you sure? What if they saw you?}
{209}{}{They didn't even check if they were being watched. They have nothing to hide.}
{210}{}{Perhaps, but I didnít see anything wrong with them.}
{211}{}{[Nods] Good work, citizen }
{212}{}{. You carried out your duty. I, and all of Vault City, thank you.}
{213}{}{Always happy to help!}
{214}{}{Do I get anything for my trouble?}

{215}{}{You didn't work that hard. Do you really think you deserve a reward?}
{216}{}{Fine, whatever you say...}
{217}{}{Look whoís talking...}

{218}{}{You did your due duty, and yet you ask for a reward? [he leans in close] I think... I can do something for you.}
{219}{}{I need 9mm ammo.}
{220}{}{I need 10mm ammo.}
{221}{}{I need money from the wasteland.}
{222}{}{I donít need anything for now.}
{223}{}{Of course. Here, take it.}
{224}{}{Thanks.}
{225}{}{Have a nice day, citizen }
{226}{}{.}
{227}{}{Iím not allowed to discuss commissions affairs. If you wanted to help, youíre too late anyway - the latest case is closed due to lack of evidence.}
{228}{}{Uh-huh. Iíd like to ask something else.}

#Female character
{1110}{}{Yes, citizen? What do you want?}
{1121}{}{Not yet, citizen. Donít worry.}
{1123}{}{Excluding some past events, the city is completely crime free. Don't worry, citizen.}
{1134}{}{Wait, I changed my mind. What about those citizens? How are they suspicious?}
{1209}{}{They didn't even check if they were being watched. They have nothing to hide.}
{1211}{}{[Nods] Good work, citizen }
{1213}{}{Glad to help!}
{1225}{}{Have a nice day, citizen }
