{100}{}{You see a greeter.}
{101}{}{You see a greeter of the slave ring and his bartender in arms.}

{110}{}{Come in. Ring is out in that hall.}
{111}{}{Show me, what do you have for a drink.}
{112}{}{Okay.}
{113}{}{That’s enough. If you're going to vomit - do it outside. Okay?}
{114}{}{I need more drink.}
{115}{}{Okay.}

{116}{}{Have you heard, slavers are no more?}
{117}{}{Yes, I heard it. I can't even imagine, who could have done that. But I'm more worried about what will happen to the ring now. I suppose, the owner will continue business, but there won't be any slaves fighting, only free fighters. Which is not bad, honestly speaking.}
