{100}{}{You see a caravan merchant.}

#Описание, когда ГГ НЕ известно о Черном Караване
{101}{}{You see a suspicious caravan merchant. What is he doing here?}

#Описание, когда ГГ известно о Черном Караване
{102}{}{You see a caravan merchant from the Black Caravan. He is clearly here for the dope.}

#Когда впервые увидят ГГ
{103}{}{Hey, you! I can see you!}
{104}{}{Got you, bitch!!}
{105}{}{Alarm! Outsider!}
{106}{}{I didn’t invite you here!}
{107}{}{Diversion!?}
{108}{}{I have you in my sight! You won't last long!}
{109}{}{Guards! Outsider!}
{110}{}{Fuck, the cops are here!}
