{100}{}{You see a citizen.}
{101}{}{You see an ordinary citizen.}
{102}{}{Sorry, I'm in a hurry.}

#–еплики при попытке заговорить, когда копа убили:
{150}{}{They say the shots came from the roof}
{151}{}{It seems like they saw a sniper on the casino roof. Strange.}
{152}{}{It happened so suddenly!}
{153}{}{For a long time, no one in the Clean City has been killed, especially a cop.}
{154}{}{No one expected this here...}
{155}{}{Who could have done it?}
