{100}{}{You see a jug of water.}
{101}{}{You see a vessel for prisoners, filled with rotten water. Apparently, the police leave good water for themselves.}
{102}{}{Careful study of this vessel makes it clear how the police treat the prisoners. The quality of water speaks for itself.}
{103}{}{The water is of a pretty crappy quality. Apparently, only people, who are put in an isolation ward, drink it. If you poison this water, you can cause a sickness among the prisoners.}
{104}{}{You poisoned the water reserved exclusively for prisoners. This can lead to serious consequences.}
