{100}{}{You see the account book.}
{101}{}{You see a casino account book. Here are recorded debts and customer winnings.}
{102}{}{These boring records do not matter to you.}
{103}{}{Taking advantage of the opportunity, you secretly tear out the page where Irvin and Murphy are mentioned.}
{104}{}{In this account book should definitely be information on Irvine and Murphy, but the cashier will not let you openly familiarize yourself with it.}
