{100}{}{The trader will not let you delve into her cart.}
{101}{}{Obviously, fixing this cart without additional scrap will not work.}
{102}{}{You don't see the need to do this.}
{103}{}{This cart is no longer needs to be repaired.}
{104}{}{With your skills, you can only do harm here.}
{105}{}{This is not the best solution.}
{106}{}{You successfully repaired the cart, replacing some parts.}
{107}{}{Done}
