{101}{}{This arcade machine is off. The sign reads "Out of order".}
{102}{}{This arcade machine now works and gives people the joy of gambling.}
{103}{}{Not during combat.}
{104}{}{Out of order}
{105}{}{The machine is in working order}
{106}{}{The machine is in working order and does its task well.}
{107}{}{This machine is broken. If you want to tinker with it, you'll have to ask permission.}
{108}{}{This requires an integrated approach}
{109}{}{Done}
{110}{}{You repaired the PCB, cleaned the registry of unnecessary data and restored the program.}
{111}{}{Something slips away from you when you try to understand the essence of the problem. It's needed to have versatile skills here.}
