{100}{}{You see: Medical Computer}
{101}{}{You see the clinic's computer - for authorized medical personnel only!}

#Overall
{120}{}{You see the medical computer. It contains clinical information about all citizens: reproduction charts, scheduled reports and other stuff you don't really care about.}
{121}{}{Read the medical report on the servants from Gerlach.}
{122}{}{Study research on mutations.}
{123}{}{Look through the blacklist.}
{124}{}{Study information from the primary database.}
{125}{}{[Leave]}

#Gerlachtown Servants
{130}{}{It turns out they're in quite sorry condition.}
{131}{}{General conclusion.}
{132}{}{Mutagen analysis.}
{133}{}{Psychological analysis.}
{134}{}{Prescribed treatments.}
{135}{}{Recommendation for all citizens.}
{136}{}{Back to Main Menu.}

{140}{}{Upon arrival to the vault, the medical condition of Gerlach residents was unsatisfactory, likely due to environmental ecology, a hectic lifestyle, lifelong lack of medical support and malnutrition. The estimated lifespan of an average Gerlach resident does not exceed 50 years at best. Most would die from cardiovascular pathologies and malignant tumors, observed in them. After initial diagnostics servants were isolated to undergo disinfection. All servants are now put under the purview of Dr. Willmouth.}
{141}{}{Most mutations are genetic in nature. They cannot be transferred except to the servant's offspring and are a causal factor for the observed tumors. Mutations are caused by radiation in 94% of cases and some unknown but non-transferrable virus in 6% of cases.}
{142}{}{Servants are experiencing an identity crisis due to lack of self-realization. Each of them suffers from serious depression. Servants are also psychologically unstable and prone to anger. They clearly have no self-control or restraints on their agressive actions.}
{143}{}{Recommendations: 1. Regular check-ups, with focus on dynamics of cells mutation. 2. Regular treatments against radiation exposure. 3. Chemical suppression of emotions, particularly self-motivation and drive for self-realization. 4. Strict work schedule.}
{144}{}{Recommendations: 1. Avoid and and all physical contact with servants. In case of contact, wash point of contact with clean water and report to medical services immediately. 2. Avoid communicating with servants, apart from direct orders concerning work. 3. Do not show emotions around the servants, especially fear. 4. Suppress any attempts by servants to act of their own volition and prevent servants from expressing self-identity.}

#MC's Condition
{160}{}{Look through your medical history.}
{161}{}{You can't make heads or tails of this medical mumbo-jumbo.}
{162}{}{[Leave]}
{163}{}{You find Dr. Willmouth's report on your condition when you were brought back to the city. When you arrived, your mental abilities were equivalent to those of a two-year old. You couldn't eat, walk, speak, or remember anything. You were diagnosed with brain damage caused by a direct electromagnetic pulse, delivered by a microchip implanted in your brain which was removed during surgery. It was impossible to restore your memory, so Dr. Willmouth carried out a special procedure to overwrite your brain with a new, artificial personality.}
{164}{}{Holy!..}
