{100}{}{Covered wagon.}
{101}{}{Cart with baggage, tightly covered with tent, so no one could see, what’s inside.}
{102}{}{Hmm... Are you sure you want to do that?}
{103}{}{Not in combat!}
{104}{}{You won’t get anything from this wagon.}

#ïîñëå şçàíüÿ ïîâîçêè
{105}{}{You see a caravan wagon, but it contains not the things many would have thought it would carry!}
{106}{}{[Hide in the wagon and wait for the caravan merchants to move out]}
{107}{}{Oh! Now I know, who supplies drugs to Vegas.}
{108}{}{Leave it alone.}

{109}{}{Just a wagon. What next?}
{110}{}{You have found the supplier of drugs in Vegas. Interesting, would the police want to know about this?}

{111}{}{This wagon is now just a junk, because it's owners are dead and the content is stolen.}
{112}{}{}
{113}{}{Just useless junk}
{114}{}{It seems it’s just junk... Why they transport it?}
{115}{}{Empty}
{116}{}{Watch the wagons, who knows...}
