{100}{}{This is the access console.}
{101}{}{You see the access console to the elevator.}
{102}{}{Access granted.}
{103}{}{Pushing on random buttons, you have not achieved anything. This is some tricky system.}
{104}{}{This requires a scientific approach.}
{105}{}{Mechanical lockpicks do not help in working with electronic equipment.}
{106}{}{The system recognizes your pass and removes the lock from the elevator.}
{107}{}{You smartly bypass the logical circuit by creating an alternative account. The system removes the lock from the elevator.}
{108}{}{You try to bypass the system, but this does not work.}
{109}{}{This system is too complicated for you.}
