{100}{}{You see the archive terminal.}
{101}{}{You see the terminal, that stores City Hall's archives. Access rights are needed in order to use it.}
{102}{}{Only the archive staff have the access to use this terminal.}

{103}{}{Here is a terminal storing a part of the City Hall archives in digital form.}
{104}{}{[Search Area 51 coordinates]}
{105}{}{[Quit]}

{106}{}{You got the coordinates, and can now travel to Area 51.}
{107}{}{Search ended.}
