{100}{}{You see a table with parts.}
{101}{}{You see a table with all kind of junk on it.}
{102}{}{This workbench is now useless.}
{103}{}{You cannot examine this table during combat.}

{110}{}{Someone has transformed this table into a weapon workbench. You see weirdly looking gun and a few notes around, which are clearly not enough to fix it.}
{111}{}{[Look closer]}
{112}{}{[Leave]}

{113}{}{This pistol is very unusual. And it’s clearly energy-based weapon. The barely seen sign on the side reads: "Property of Area 51".}
{114}{}{[Next]}
{115}{}{The weapon won't fire, even though it's charged. It seems that this task can only be handled by a person with vast experience in the repairing of energy weapons.}
{116}{}{[Take the blaster]}

{117}{}{You take the gun with all its parts, including charging power cells.}
{118}{}{The owner won’t be happy, but I need this more!}
