{110}{}{"Vending machine offers a wide range of various exciting and informative publications."}
{111}{}{[Select publication]}
{112}{}{[Leave the machine alone]}
{113}{}{Sorry, currently there is no item in the machine.}
{114}{}{"To make a purchase, select the number of the desired publication and insert the required amount of money in the slot. "(The price of each unit is - 500$)}
{115}{}{"Thank you for your purchase! We wish you a pleasant reading."}
{116}{}{[Back to the choice of publications]}
{117}{}{[Empty slot]}
{118}{}{.}
{119}{}{"Please insert the required amount of money in the slot."}
{120}{}{Obviously, I do not have that kind of money.}
{121}{}{[Pay]}
{122}{}{> Next list}
{123}{}{< Previous list}
