{100}{}{Oxygen cylinders.}
{101}{}{Cylinders with emergency oxygen supply. Each has the word "EXPLOSIVE!" written in large letters.}
{102}{}{You could prepare the cart to explode and push it in the direction of turrets.}
{103}{}{Cylinders with emergency oxygen supply. They can be pushed to the turrets and blown up, but how to do that from a distance?}
{104}{}{Looks like here comes the boom!}
{105}{}{Nothing.}
{106}{}{You cannot do that during combat!}
{107}{}{You set the dynamite to the cart. All that's left is to set the timer and give a little push to this dangerous "baggage".}
{108}{}{Mined}
{109}{}{You already mined the cart, additional charges are not required.}
{110}{}{That is unnecessary}
{111}{}{You attached the cable to the gas cylinders and pushed the cart. All that's left is to give it a little charge.}
