{110}{}{You see a device for distribution of power through the upper levels. Without it, the vault will have no power.}
{111}{}{The device does not work, and it’s your fault!}
{112}{}{You've already disconnected the power from this distributor.}
{113}{}{You disable this distributor and hear the hum from the wires in the vault grows quiet.}
{114}{}{You have very little time left before the backup generators turn on.}
{115}{}{**WARNING! BACKUP GENERATORS ACTIVATED!*}
{116}{}{You will not be able to turn off the distributor, your technical skills are not good enough.}
{117}{}{That won’t do anything.}

{118}{}{The device does not work}
{119}{}{This is an important thing}
{120}{}{Done}
{121}{}{Not clear}
{122}{}{That won't work here.}
{123}{}{The explosives should be placed *under* the device.}
{124}{}{Not working}
