#Кажется, текст не используется в 1.0., но не уверен полностью
{100}{}{There is only bundles of high-voltage cables here.}
{101}{}{Just some wires}
{102}{}{There's nothing here but empty boxes from the cables.}
{103}{}{Empty}
{104}{}{In the boxes are cables and connectors for connections. Why do you need them?}
{105}{}{Cunning plan!}
{106}{}{That is true. Leave the box alone.}
{107}{}{Really, this will be enchanting victory over the turrets! You tie the cable with one end to the trolley with the cylinders, the other to the switchgear in the hallway. Slightly open the cylinder valves and push the cart. You can simply turn on the current in the cable.}
{108}{}{Perform these simple actions.}
{109}{}{Leave.}
{110}{}{You attach the cable to the gas cylinders. All that;s left is to give it a little charge.}