{100}{}{You see a punching bag.}
{101}{}{You see a punching bag. It's like inviting you to try it out. You almost hear "Don't miss the opportunity!" in your head.}
{102}{}{You can warm up your fists and try out new methods of fighting on this bag.}
{103}{}{Hmm, why not?}
{104}{}{The bag was so dilapidated after your training that it became unusable.}
{105}{}{This bag is useless}
{106}{}{This bag could be useful for your skills, but they are already too high.}
{107}{}{Training? I don't need this anymore...}
{108}{}{You spend two hours in training and increase your unarmed skill by 5%.}
{109}{}{Good work!}