{100}{}{You see surveillance monitor screen.}
{101}{}{You see surveillance monitor screens tracking vault's rooms.}

{110}{}{You see surveillance monitor screens tracking vault's rooms. The screens show corridors and some public spaces.}
{111}{}{[Examine 2nd level]}
{112}{}{[Examine 3rd level]}
{113}{}{[Examine 4th level]}
{114}{}{[Leave]}

{120}{}{On the second level there are residential and recreational rooms. There is huge mess in these rooms, apparently cleaning wasn't conducted in many years. At the end of the main corridor, near the elevator, the wall collapsed from the blast.}
{121}{}{On the third level there are technical and service rooms, including the overseer's post and power station.}
{122}{}{The fourth level is not monitored. The feel of mystery and malice doesn't leave you.}
