{100}{}{You see a caravan merchant.}
{101}{}{You see a caravan merchant with a very busy look.}

{105}{}{You failed to collect items for the local caravan - the group has already departed.}
{106}{}{Because of the death of the caravan completing the task to collect items is now impossible.}
{107}{}{Thanks for the help.}

#До квеста
{110}{}{Huh? I don’t have time now, we have the walk whole city around before moving out.}
{111}{}{If you do not have time, I can help you.}
{112}{}{[Leave]}
{113}{}{Would be great. Listen, I need to collect a whole list of things before the road. If you find them, I'll pay a hundred bucks for your trouble. Deal?}
{114}{}{Deal. Give me the list, I'll write it in my Pip-Boy.}
{115}{}{No, running after things is boring. Goodbye.}
{116}{}{Great, here is my list. Try to do it as quickly as possible! My caravan is here only for three days before moving out. If you're late with the job, then we just leave and all your work will be useless.}
{117}{}{So, three days to collect things. I'll try to remember.}
{118}{}{Can't you simply walk past? Don't want to have anything to do with people who have a reputation worse than the brahmin's ass.}
{119}{}{Uh, okay.}

#Во время квеста
{120}{}{Oh, it's you. How are you doing with the inventory collection?}
{121}{}{Nearly ready. There are }
{122}{}{ entries left on the list. Wait a little longer.}
{123}{}{Nothing yet, but I remember. Will come back when I have everything.}
{124}{}{Job is done - here are all the things you ordered.}
{125}{}{Okay. But I remind you - we're going soon. If you don't finish in time, then blame yourself.}
{126}{}{Okay.}
{127}{}{All done? Wonderful! Here is the payment for items and courier work. Thank you, you helped me a lot.}
{128}{}{You're welcome.}

{129}{}{And yet something is missing. Check again.}
{130}{}{Hmm...}
