{100}{}{You see caravaneer.}
{101}{}{You see a cute caravaneer girl.}

{110}{}{Hi there! Thanks to you, we decided to occasionally visit the Bridgeport to trade. Also, we'll give you a 5% discount.}
{111}{}{You're welcome.}

{112}{}{How are you doing, friend?}
{113}{}{Will you now trade in Bridgeport more often?}
{114}{}{As long as we have clients, we will. Agreed to visit here around every 15th of the month. Resting couple of days, then hit the road again. }
{115}{}{Show me your goods.}
{116}{}{That's it? Gee, haven't even had a real trade.}
{117}{}{Alright, I will leave you for now. See you around.}
{118}{}{Let's look at your stuff.}
{119}{}{We don't do business with the likes of you! Get lost!}

#Женские реплики
{1112}{}{Hey! How are you doing, friend?}
