{100}{}{Useless}
{101}{}{You cannot open this door.}
{102}{}{First you must talk to that man.}

#Для дверей в Вегасе на карте работорговцев
{103}{}{You see boarded-up door.}
{104}{}{This door is firmly nailed to the doorpost.}

#Для дверей лифта на дамбе
{105}{}{You see the door of the service elevator.}
{106}{}{This elevator takes to the lower levels of the dam. You have no business there.}

#Для дверей в Офисе Интерплей
{107}{}{You see armored door.}
{108}{}{This door is heavily reinforced, it cannot be knocked out. There is a sign hanging above: "Spammers are not allowed!"}

#Для дверей в убежище 8
{109}{}{You see an elevator door.}
{110}{}{This elevator takes to the lower levels of the vault, but you don’t have the code for the activation.}
