{100}{}{This thing should be used on a person.}
{101}{}{You get }
{102}{}{ experience points for testing mutagenic serum.}
{103}{}{That was... Wittily.}
{104}{}{No need to dismember the corpse.}

{105}{}{You shouldn't have waved your weapon in front of a victim!}
{106}{}{The victim found you too early.}
{107}{}{Luck has left you.}
{108}{}{You can't do this during combat.}
{109}{}{What the hell you're doing!?}
{110}{}{What, so eager to die!?}
