{100}{}{You can't use this device during combat.}
{101}{}{This device can only be used while holding it in hands.}

{102}{}{You have depleted you heavy bullets stock.}

#Menu options
{110}{}{The ammo press is ready for use. Choose your caliber.}
{111}{}{leave it.}
{112}{}{Finish.}

{113}{}{Make bullet ammo.}

{114}{}{To produce one set of ammo is required }
{115}{}{ components. In the backpack you have }
{116}{}{ components.}
{117}{}{}
{118}{}{Produce armor piercing ammo.}
{119}{}{Produce one set of ammo.}

{120}{}{Done.}
{121}{}{Go back to caliber list.}
{122}{}{Again.}
{123}{}{Next list.}
{124}{}{Previous list.}

#Caliber choosing
{200}{}{}
{201}{}{10 mm}
{202}{}{12 gauge}
{203}{}{0.44 Magnum}
{204}{}{0,223}
{205}{}{0,30 rifle}
{206}{}{9 mm}
{207}{}{}
{208}{}{0,45}
{209}{}{5 mm}
{210}{}{12 gauge coin shot (uses heavy bullets)}
